// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: bed.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 抢占床位 - 请求
type OccupyBedSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BedId         uint64                 `protobuf:"varint,1,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupyBedSlotRequest) Reset() {
	*x = OccupyBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupyBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupyBedSlotRequest) ProtoMessage() {}

func (x *OccupyBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupyBedSlotRequest.ProtoReflect.Descriptor instead.
func (*OccupyBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{0}
}

func (x *OccupyBedSlotRequest) GetBedId() uint64 {
	if x != nil {
		return x.BedId
	}
	return 0
}

func (x *OccupyBedSlotRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// 抢占床位 - 回复
type OccupyBedSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupyBedSlotResponse) Reset() {
	*x = OccupyBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupyBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupyBedSlotResponse) ProtoMessage() {}

func (x *OccupyBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupyBedSlotResponse.ProtoReflect.Descriptor instead.
func (*OccupyBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{1}
}

func (x *OccupyBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 抢占床位 - 通知发起者以外的所有人
type OccupyBedSlotNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint64                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	BedId         uint64                 `protobuf:"varint,2,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
	SlotId        uint32                 `protobuf:"varint,3,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	BaseRole      *BaseRoleInfo          `protobuf:"bytes,4,opt,name=base_role,json=baseRole,proto3" json:"base_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupyBedSlotNotify) Reset() {
	*x = OccupyBedSlotNotify{}
	mi := &file_bed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupyBedSlotNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupyBedSlotNotify) ProtoMessage() {}

func (x *OccupyBedSlotNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupyBedSlotNotify.ProtoReflect.Descriptor instead.
func (*OccupyBedSlotNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{2}
}

func (x *OccupyBedSlotNotify) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *OccupyBedSlotNotify) GetBedId() uint64 {
	if x != nil {
		return x.BedId
	}
	return 0
}

func (x *OccupyBedSlotNotify) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *OccupyBedSlotNotify) GetBaseRole() *BaseRoleInfo {
	if x != nil {
		return x.BaseRole
	}
	return nil
}

// 申请床位请求 - 通知床位所有者，有人向你申请加入
type ApplyBedSlotNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRole      *BaseRoleInfo          `protobuf:"bytes,1,opt,name=base_role,json=baseRole,proto3" json:"base_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyBedSlotNotify) Reset() {
	*x = ApplyBedSlotNotify{}
	mi := &file_bed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBedSlotNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBedSlotNotify) ProtoMessage() {}

func (x *ApplyBedSlotNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBedSlotNotify.ProtoReflect.Descriptor instead.
func (*ApplyBedSlotNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyBedSlotNotify) GetBaseRole() *BaseRoleInfo {
	if x != nil {
		return x.BaseRole
	}
	return nil
}

// 同意申请床位 - 请求
type AgreeApplyBedSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint64                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgreeApplyBedSlotRequest) Reset() {
	*x = AgreeApplyBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgreeApplyBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeApplyBedSlotRequest) ProtoMessage() {}

func (x *AgreeApplyBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeApplyBedSlotRequest.ProtoReflect.Descriptor instead.
func (*AgreeApplyBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{4}
}

func (x *AgreeApplyBedSlotRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 同意申请床位 - 回复
type AgreeApplyBedSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgreeApplyBedSlotResponse) Reset() {
	*x = AgreeApplyBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgreeApplyBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeApplyBedSlotResponse) ProtoMessage() {}

func (x *AgreeApplyBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeApplyBedSlotResponse.ProtoReflect.Descriptor instead.
func (*AgreeApplyBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{5}
}

func (x *AgreeApplyBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 拒绝申请床位 - 请求
type RejectApplyBedSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint64                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplyBedSlotRequest) Reset() {
	*x = RejectApplyBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplyBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplyBedSlotRequest) ProtoMessage() {}

func (x *RejectApplyBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplyBedSlotRequest.ProtoReflect.Descriptor instead.
func (*RejectApplyBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{6}
}

func (x *RejectApplyBedSlotRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 拒绝申请床位 - 回复
type RejectApplyBedSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplyBedSlotResponse) Reset() {
	*x = RejectApplyBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplyBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplyBedSlotResponse) ProtoMessage() {}

func (x *RejectApplyBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplyBedSlotResponse.ProtoReflect.Descriptor instead.
func (*RejectApplyBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{7}
}

func (x *RejectApplyBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 封印床位 - 请求
type SealBedSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 床位 id
	SlotId        int32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealBedSlotRequest) Reset() {
	*x = SealBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealBedSlotRequest) ProtoMessage() {}

func (x *SealBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealBedSlotRequest.ProtoReflect.Descriptor instead.
func (*SealBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{8}
}

func (x *SealBedSlotRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// 封印床位 - 回应
type SealBedSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	SlotId        int32                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	State         *BedSealState          `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealBedSlotResponse) Reset() {
	*x = SealBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealBedSlotResponse) ProtoMessage() {}

func (x *SealBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealBedSlotResponse.ProtoReflect.Descriptor instead.
func (*SealBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{9}
}

func (x *SealBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SealBedSlotResponse) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SealBedSlotResponse) GetState() *BedSealState {
	if x != nil {
		return x.State
	}
	return nil
}

// 封印床位 - 通知
type SealBedSlotNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	State         *BedSealState          `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealBedSlotNotify) Reset() {
	*x = SealBedSlotNotify{}
	mi := &file_bed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealBedSlotNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealBedSlotNotify) ProtoMessage() {}

func (x *SealBedSlotNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealBedSlotNotify.ProtoReflect.Descriptor instead.
func (*SealBedSlotNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{10}
}

func (x *SealBedSlotNotify) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SealBedSlotNotify) GetState() *BedSealState {
	if x != nil {
		return x.State
	}
	return nil
}

// 解封床位 - 请求
type UnsealBedSlotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 床位id
	SlotId        int32 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealBedSlotRequest) Reset() {
	*x = UnsealBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealBedSlotRequest) ProtoMessage() {}

func (x *UnsealBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealBedSlotRequest.ProtoReflect.Descriptor instead.
func (*UnsealBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{11}
}

func (x *UnsealBedSlotRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// 解封床位 - 回应
type UnsealBedSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                  // 业务错误码（如：床位未被封，不可解封等）
	SlotId        int32                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 id
	State         *BedSealState          `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                  // 解封后的最新状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealBedSlotResponse) Reset() {
	*x = UnsealBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealBedSlotResponse) ProtoMessage() {}

func (x *UnsealBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealBedSlotResponse.ProtoReflect.Descriptor instead.
func (*UnsealBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{12}
}

func (x *UnsealBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UnsealBedSlotResponse) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *UnsealBedSlotResponse) GetState() *BedSealState {
	if x != nil {
		return x.State
	}
	return nil
}

// 解封床位 - 通知（广播给房间内所有人）
type UnsealBedSlotNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 id
	State         *BedSealState          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                  // 最新状态（通常 is_sealed = false）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealBedSlotNotify) Reset() {
	*x = UnsealBedSlotNotify{}
	mi := &file_bed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealBedSlotNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealBedSlotNotify) ProtoMessage() {}

func (x *UnsealBedSlotNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealBedSlotNotify.ProtoReflect.Descriptor instead.
func (*UnsealBedSlotNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{13}
}

func (x *UnsealBedSlotNotify) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *UnsealBedSlotNotify) GetState() *BedSealState {
	if x != nil {
		return x.State
	}
	return nil
}

// 踢出床位上的角色 - 请求
type KickBedSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`       // 被踢的床位 ID
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 操作目标用户 ID（可选：若踢全员，可忽略）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickBedSlotRequest) Reset() {
	*x = KickBedSlotRequest{}
	mi := &file_bed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickBedSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickBedSlotRequest) ProtoMessage() {}

func (x *KickBedSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickBedSlotRequest.ProtoReflect.Descriptor instead.
func (*KickBedSlotRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{14}
}

func (x *KickBedSlotRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *KickBedSlotRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 踢出床位上的角色 - 回复
type KickBedSlotResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Error  *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                  // 错误码（如：床位无人、保护不足、不够能量等）
	SlotId uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 ID
	// 护盾最大值和当前值
	MaxValue      int64           `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	CurValue      int64           `protobuf:"varint,4,opt,name=cur_value,json=curValue,proto3" json:"cur_value,omitempty"`
	Roles         []*BaseRoleInfo `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"` // 被踢下的所有角色信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickBedSlotResponse) Reset() {
	*x = KickBedSlotResponse{}
	mi := &file_bed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickBedSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickBedSlotResponse) ProtoMessage() {}

func (x *KickBedSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickBedSlotResponse.ProtoReflect.Descriptor instead.
func (*KickBedSlotResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{15}
}

func (x *KickBedSlotResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *KickBedSlotResponse) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *KickBedSlotResponse) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *KickBedSlotResponse) GetCurValue() int64 {
	if x != nil {
		return x.CurValue
	}
	return 0
}

func (x *KickBedSlotResponse) GetRoles() []*BaseRoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 踢出床位上的角色 - 通知所有人（除了发起者）
type KickBedSlotNotify struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SlotId uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 被踢的床位 ID
	// 护盾最大值和当前值
	MaxValue      int64           `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	CurValue      int64           `protobuf:"varint,3,opt,name=cur_value,json=curValue,proto3" json:"cur_value,omitempty"`
	Roles         []*BaseRoleInfo `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"` // 被踢下的所有角色信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickBedSlotNotify) Reset() {
	*x = KickBedSlotNotify{}
	mi := &file_bed_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickBedSlotNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickBedSlotNotify) ProtoMessage() {}

func (x *KickBedSlotNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickBedSlotNotify.ProtoReflect.Descriptor instead.
func (*KickBedSlotNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{16}
}

func (x *KickBedSlotNotify) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *KickBedSlotNotify) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *KickBedSlotNotify) GetCurValue() int64 {
	if x != nil {
		return x.CurValue
	}
	return 0
}

func (x *KickBedSlotNotify) GetRoles() []*BaseRoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 增加床位护盾 - 请求
type AddBedSlotShieldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBedSlotShieldRequest) Reset() {
	*x = AddBedSlotShieldRequest{}
	mi := &file_bed_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBedSlotShieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBedSlotShieldRequest) ProtoMessage() {}

func (x *AddBedSlotShieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBedSlotShieldRequest.ProtoReflect.Descriptor instead.
func (*AddBedSlotShieldRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{17}
}

func (x *AddBedSlotShieldRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// 增加床位护盾 - 回复
type AddBedSlotShieldResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Error  *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                  // 错误码
	SlotId uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 ID
	// 增加后的护盾最大值与当前值
	MaxValue      int64 `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	CurValue      int64 `protobuf:"varint,4,opt,name=cur_value,json=curValue,proto3" json:"cur_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBedSlotShieldResponse) Reset() {
	*x = AddBedSlotShieldResponse{}
	mi := &file_bed_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBedSlotShieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBedSlotShieldResponse) ProtoMessage() {}

func (x *AddBedSlotShieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBedSlotShieldResponse.ProtoReflect.Descriptor instead.
func (*AddBedSlotShieldResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{18}
}

func (x *AddBedSlotShieldResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AddBedSlotShieldResponse) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AddBedSlotShieldResponse) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *AddBedSlotShieldResponse) GetCurValue() int64 {
	if x != nil {
		return x.CurValue
	}
	return 0
}

// 增加床位护盾 - 通知所有人
type AddBedSlotShieldNotify struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SlotId uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 床位 ID
	// 增加后的护盾最大值与当前值
	MaxValue      int64 `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	CurValue      int64 `protobuf:"varint,3,opt,name=cur_value,json=curValue,proto3" json:"cur_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBedSlotShieldNotify) Reset() {
	*x = AddBedSlotShieldNotify{}
	mi := &file_bed_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBedSlotShieldNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBedSlotShieldNotify) ProtoMessage() {}

func (x *AddBedSlotShieldNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBedSlotShieldNotify.ProtoReflect.Descriptor instead.
func (*AddBedSlotShieldNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{19}
}

func (x *AddBedSlotShieldNotify) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AddBedSlotShieldNotify) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *AddBedSlotShieldNotify) GetCurValue() int64 {
	if x != nil {
		return x.CurValue
	}
	return 0
}

// 下发床位信息列表 - 进入直播间时下发
type BedInfoListSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BedList       []*BedInfo             `protobuf:"bytes,1,rep,name=bed_list,json=bedList,proto3" json:"bed_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedInfoListSync) Reset() {
	*x = BedInfoListSync{}
	mi := &file_bed_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedInfoListSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedInfoListSync) ProtoMessage() {}

func (x *BedInfoListSync) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedInfoListSync.ProtoReflect.Descriptor instead.
func (*BedInfoListSync) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{20}
}

func (x *BedInfoListSync) GetBedList() []*BedInfo {
	if x != nil {
		return x.BedList
	}
	return nil
}

// 发起 PK - 请求
type BedSlotPKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`       // 参与 PK 的床位 ID
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 被挑战玩家 ID（床位占有者）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedSlotPKRequest) Reset() {
	*x = BedSlotPKRequest{}
	mi := &file_bed_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedSlotPKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedSlotPKRequest) ProtoMessage() {}

func (x *BedSlotPKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedSlotPKRequest.ProtoReflect.Descriptor instead.
func (*BedSlotPKRequest) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{21}
}

func (x *BedSlotPKRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *BedSlotPKRequest) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// 发起 PK - 回应
type BedSlotPKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 错误码：床位无人、对方保护、PK 冷却中等
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedSlotPKResponse) Reset() {
	*x = BedSlotPKResponse{}
	mi := &file_bed_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedSlotPKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedSlotPKResponse) ProtoMessage() {}

func (x *BedSlotPKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedSlotPKResponse.ProtoReflect.Descriptor instead.
func (*BedSlotPKResponse) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{22}
}

func (x *BedSlotPKResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BedSlotPKResponse) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

// 开始 PK - 通知所有人
type BedSlotPKStartNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`          // PK 发生的床位
	Attacker      *BaseRoleInfo          `protobuf:"bytes,2,opt,name=attacker,proto3" json:"attacker,omitempty"`                     // 挑战者（发起 PK 的玩家）
	Defender      *BaseRoleInfo          `protobuf:"bytes,3,opt,name=defender,proto3" json:"defender,omitempty"`                     // 被挑战者（当前床位占有者）
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // PK 开始时间戳（毫秒或秒，可按你系统格式）
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                    // PK 持续时间（用于客户端倒计时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedSlotPKStartNotify) Reset() {
	*x = BedSlotPKStartNotify{}
	mi := &file_bed_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedSlotPKStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedSlotPKStartNotify) ProtoMessage() {}

func (x *BedSlotPKStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedSlotPKStartNotify.ProtoReflect.Descriptor instead.
func (*BedSlotPKStartNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{23}
}

func (x *BedSlotPKStartNotify) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *BedSlotPKStartNotify) GetAttacker() *BaseRoleInfo {
	if x != nil {
		return x.Attacker
	}
	return nil
}

func (x *BedSlotPKStartNotify) GetDefender() *BaseRoleInfo {
	if x != nil {
		return x.Defender
	}
	return nil
}

func (x *BedSlotPKStartNotify) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BedSlotPKStartNotify) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// PK 结束 - 通知所有人
type BedSlotPKEndNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`            // 床位 ID
	WinnerId      uint64                 `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`      // 胜利方玩家 ID
	LoserId       uint64                 `protobuf:"varint,3,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`         // 失败方玩家 ID
	WinnerRole    *BaseRoleInfo          `protobuf:"bytes,4,opt,name=winner_role,json=winnerRole,proto3" json:"winner_role,omitempty"` // 胜利方角色完整信息（展示胜利 UI）
	LoserRole     *BaseRoleInfo          `protobuf:"bytes,5,opt,name=loser_role,json=loserRole,proto3" json:"loser_role,omitempty"`    // 失败方角色信息（可作 UI 展示）
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`         // 结束时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedSlotPKEndNotify) Reset() {
	*x = BedSlotPKEndNotify{}
	mi := &file_bed_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedSlotPKEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedSlotPKEndNotify) ProtoMessage() {}

func (x *BedSlotPKEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_bed_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedSlotPKEndNotify.ProtoReflect.Descriptor instead.
func (*BedSlotPKEndNotify) Descriptor() ([]byte, []int) {
	return file_bed_proto_rawDescGZIP(), []int{24}
}

func (x *BedSlotPKEndNotify) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *BedSlotPKEndNotify) GetWinnerId() uint64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *BedSlotPKEndNotify) GetLoserId() uint64 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *BedSlotPKEndNotify) GetWinnerRole() *BaseRoleInfo {
	if x != nil {
		return x.WinnerRole
	}
	return nil
}

func (x *BedSlotPKEndNotify) GetLoserRole() *BaseRoleInfo {
	if x != nil {
		return x.LoserRole
	}
	return nil
}

func (x *BedSlotPKEndNotify) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_bed_proto protoreflect.FileDescriptor

const file_bed_proto_rawDesc = "" +
	"\n" +
	"\tbed.proto\x12\x10zeus.game.bed.v1\x1a\x0eerr_code.proto\x1a\x0ebed_type.proto\x1a\x0frole_type.proto\"F\n" +
	"\x14OccupyBedSlotRequest\x12\x15\n" +
	"\x06bed_id\x18\x01 \x01(\x04R\x05bedId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\"H\n" +
	"\x15OccupyBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\"\xa0\x01\n" +
	"\x13OccupyBedSlotNotify\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x04R\btargetId\x12\x15\n" +
	"\x06bed_id\x18\x02 \x01(\x04R\x05bedId\x12\x17\n" +
	"\aslot_id\x18\x03 \x01(\rR\x06slotId\x12<\n" +
	"\tbase_role\x18\x04 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\bbaseRole\"R\n" +
	"\x12ApplyBedSlotNotify\x12<\n" +
	"\tbase_role\x18\x01 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\bbaseRole\"7\n" +
	"\x18AgreeApplyBedSlotRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x04R\btargetId\"L\n" +
	"\x19AgreeApplyBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\"8\n" +
	"\x19RejectApplyBedSlotRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x04R\btargetId\"M\n" +
	"\x1aRejectApplyBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\"-\n" +
	"\x12SealBedSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\"\x95\x01\n" +
	"\x13SealBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x05R\x06slotId\x124\n" +
	"\x05state\x18\x03 \x01(\v2\x1e.zeus.game.bed.v1.BedSealStateR\x05state\"b\n" +
	"\x11SealBedSlotNotify\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x05R\x06slotId\x124\n" +
	"\x05state\x18\x03 \x01(\v2\x1e.zeus.game.bed.v1.BedSealStateR\x05state\"/\n" +
	"\x14UnsealBedSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\"\x97\x01\n" +
	"\x15UnsealBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x05R\x06slotId\x124\n" +
	"\x05state\x18\x03 \x01(\v2\x1e.zeus.game.bed.v1.BedSealStateR\x05state\"d\n" +
	"\x13UnsealBedSlotNotify\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\x124\n" +
	"\x05state\x18\x02 \x01(\v2\x1e.zeus.game.bed.v1.BedSealStateR\x05state\"J\n" +
	"\x12KickBedSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"\xd0\x01\n" +
	"\x13KickBedSlotResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12\x1b\n" +
	"\tmax_value\x18\x03 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tcur_value\x18\x04 \x01(\x03R\bcurValue\x125\n" +
	"\x05roles\x18\x05 \x03(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x05roles\"\x9d\x01\n" +
	"\x11KickBedSlotNotify\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tcur_value\x18\x03 \x01(\x03R\bcurValue\x125\n" +
	"\x05roles\x18\x04 \x03(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x05roles\"2\n" +
	"\x17AddBedSlotShieldRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\"\x9e\x01\n" +
	"\x18AddBedSlotShieldResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12\x1b\n" +
	"\tmax_value\x18\x03 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tcur_value\x18\x04 \x01(\x03R\bcurValue\"k\n" +
	"\x16AddBedSlotShieldNotify\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tcur_value\x18\x03 \x01(\x03R\bcurValue\"G\n" +
	"\x0fBedInfoListSync\x124\n" +
	"\bbed_list\x18\x01 \x03(\v2\x19.zeus.game.bed.v1.BedInfoR\abedList\"H\n" +
	"\x10BedSlotPKRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\"]\n" +
	"\x11BedSlotPKResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\"\xe4\x01\n" +
	"\x14BedSlotPKStartNotify\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12;\n" +
	"\battacker\x18\x02 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\battacker\x12;\n" +
	"\bdefender\x18\x03 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\bdefender\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\"\x82\x02\n" +
	"\x12BedSlotPKEndNotify\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x04R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x03 \x01(\x04R\aloserId\x12@\n" +
	"\vwinner_role\x18\x04 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\n" +
	"winnerRole\x12>\n" +
	"\n" +
	"loser_role\x18\x05 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\tloserRole\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTimeB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_bed_proto_rawDescOnce sync.Once
	file_bed_proto_rawDescData []byte
)

func file_bed_proto_rawDescGZIP() []byte {
	file_bed_proto_rawDescOnce.Do(func() {
		file_bed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bed_proto_rawDesc), len(file_bed_proto_rawDesc)))
	})
	return file_bed_proto_rawDescData
}

var file_bed_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_bed_proto_goTypes = []any{
	(*OccupyBedSlotRequest)(nil),       // 0: zeus.game.bed.v1.OccupyBedSlotRequest
	(*OccupyBedSlotResponse)(nil),      // 1: zeus.game.bed.v1.OccupyBedSlotResponse
	(*OccupyBedSlotNotify)(nil),        // 2: zeus.game.bed.v1.OccupyBedSlotNotify
	(*ApplyBedSlotNotify)(nil),         // 3: zeus.game.bed.v1.ApplyBedSlotNotify
	(*AgreeApplyBedSlotRequest)(nil),   // 4: zeus.game.bed.v1.AgreeApplyBedSlotRequest
	(*AgreeApplyBedSlotResponse)(nil),  // 5: zeus.game.bed.v1.AgreeApplyBedSlotResponse
	(*RejectApplyBedSlotRequest)(nil),  // 6: zeus.game.bed.v1.RejectApplyBedSlotRequest
	(*RejectApplyBedSlotResponse)(nil), // 7: zeus.game.bed.v1.RejectApplyBedSlotResponse
	(*SealBedSlotRequest)(nil),         // 8: zeus.game.bed.v1.SealBedSlotRequest
	(*SealBedSlotResponse)(nil),        // 9: zeus.game.bed.v1.SealBedSlotResponse
	(*SealBedSlotNotify)(nil),          // 10: zeus.game.bed.v1.SealBedSlotNotify
	(*UnsealBedSlotRequest)(nil),       // 11: zeus.game.bed.v1.UnsealBedSlotRequest
	(*UnsealBedSlotResponse)(nil),      // 12: zeus.game.bed.v1.UnsealBedSlotResponse
	(*UnsealBedSlotNotify)(nil),        // 13: zeus.game.bed.v1.UnsealBedSlotNotify
	(*KickBedSlotRequest)(nil),         // 14: zeus.game.bed.v1.KickBedSlotRequest
	(*KickBedSlotResponse)(nil),        // 15: zeus.game.bed.v1.KickBedSlotResponse
	(*KickBedSlotNotify)(nil),          // 16: zeus.game.bed.v1.KickBedSlotNotify
	(*AddBedSlotShieldRequest)(nil),    // 17: zeus.game.bed.v1.AddBedSlotShieldRequest
	(*AddBedSlotShieldResponse)(nil),   // 18: zeus.game.bed.v1.AddBedSlotShieldResponse
	(*AddBedSlotShieldNotify)(nil),     // 19: zeus.game.bed.v1.AddBedSlotShieldNotify
	(*BedInfoListSync)(nil),            // 20: zeus.game.bed.v1.BedInfoListSync
	(*BedSlotPKRequest)(nil),           // 21: zeus.game.bed.v1.BedSlotPKRequest
	(*BedSlotPKResponse)(nil),          // 22: zeus.game.bed.v1.BedSlotPKResponse
	(*BedSlotPKStartNotify)(nil),       // 23: zeus.game.bed.v1.BedSlotPKStartNotify
	(*BedSlotPKEndNotify)(nil),         // 24: zeus.game.bed.v1.BedSlotPKEndNotify
	(*Error)(nil),                      // 25: zeus.game.error.v1.Error
	(*BaseRoleInfo)(nil),               // 26: zeus.game.role.v1.BaseRoleInfo
	(*BedSealState)(nil),               // 27: zeus.game.bed.v1.BedSealState
	(*BedInfo)(nil),                    // 28: zeus.game.bed.v1.BedInfo
}
var file_bed_proto_depIdxs = []int32{
	25, // 0: zeus.game.bed.v1.OccupyBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	26, // 1: zeus.game.bed.v1.OccupyBedSlotNotify.base_role:type_name -> zeus.game.role.v1.BaseRoleInfo
	26, // 2: zeus.game.bed.v1.ApplyBedSlotNotify.base_role:type_name -> zeus.game.role.v1.BaseRoleInfo
	25, // 3: zeus.game.bed.v1.AgreeApplyBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	25, // 4: zeus.game.bed.v1.RejectApplyBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	25, // 5: zeus.game.bed.v1.SealBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	27, // 6: zeus.game.bed.v1.SealBedSlotResponse.state:type_name -> zeus.game.bed.v1.BedSealState
	27, // 7: zeus.game.bed.v1.SealBedSlotNotify.state:type_name -> zeus.game.bed.v1.BedSealState
	25, // 8: zeus.game.bed.v1.UnsealBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	27, // 9: zeus.game.bed.v1.UnsealBedSlotResponse.state:type_name -> zeus.game.bed.v1.BedSealState
	27, // 10: zeus.game.bed.v1.UnsealBedSlotNotify.state:type_name -> zeus.game.bed.v1.BedSealState
	25, // 11: zeus.game.bed.v1.KickBedSlotResponse.error:type_name -> zeus.game.error.v1.Error
	26, // 12: zeus.game.bed.v1.KickBedSlotResponse.roles:type_name -> zeus.game.role.v1.BaseRoleInfo
	26, // 13: zeus.game.bed.v1.KickBedSlotNotify.roles:type_name -> zeus.game.role.v1.BaseRoleInfo
	25, // 14: zeus.game.bed.v1.AddBedSlotShieldResponse.error:type_name -> zeus.game.error.v1.Error
	28, // 15: zeus.game.bed.v1.BedInfoListSync.bed_list:type_name -> zeus.game.bed.v1.BedInfo
	25, // 16: zeus.game.bed.v1.BedSlotPKResponse.error:type_name -> zeus.game.error.v1.Error
	26, // 17: zeus.game.bed.v1.BedSlotPKStartNotify.attacker:type_name -> zeus.game.role.v1.BaseRoleInfo
	26, // 18: zeus.game.bed.v1.BedSlotPKStartNotify.defender:type_name -> zeus.game.role.v1.BaseRoleInfo
	26, // 19: zeus.game.bed.v1.BedSlotPKEndNotify.winner_role:type_name -> zeus.game.role.v1.BaseRoleInfo
	26, // 20: zeus.game.bed.v1.BedSlotPKEndNotify.loser_role:type_name -> zeus.game.role.v1.BaseRoleInfo
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_bed_proto_init() }
func file_bed_proto_init() {
	if File_bed_proto != nil {
		return
	}
	file_err_code_proto_init()
	file_bed_type_proto_init()
	file_role_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bed_proto_rawDesc), len(file_bed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bed_proto_goTypes,
		DependencyIndexes: file_bed_proto_depIdxs,
		MessageInfos:      file_bed_proto_msgTypes,
	}.Build()
	File_bed_proto = out.File
	file_bed_proto_goTypes = nil
	file_bed_proto_depIdxs = nil
}
