// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: bed_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 床位灵气状态
type BedAuraState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuraMaxValue  int64                  `protobuf:"varint,1,opt,name=aura_max_value,json=auraMaxValue,proto3" json:"aura_max_value,omitempty"` // 灵气上限（随品质变化）
	AuraCurValue  int64                  `protobuf:"varint,2,opt,name=aura_cur_value,json=auraCurValue,proto3" json:"aura_cur_value,omitempty"` // 当前灵气值
	ResetAt       int64                  `protobuf:"varint,3,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`                  // 下次重置时间（如每日 0 点）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedAuraState) Reset() {
	*x = BedAuraState{}
	mi := &file_bed_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedAuraState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedAuraState) ProtoMessage() {}

func (x *BedAuraState) ProtoReflect() protoreflect.Message {
	mi := &file_bed_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedAuraState.ProtoReflect.Descriptor instead.
func (*BedAuraState) Descriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{0}
}

func (x *BedAuraState) GetAuraMaxValue() int64 {
	if x != nil {
		return x.AuraMaxValue
	}
	return 0
}

func (x *BedAuraState) GetAuraCurValue() int64 {
	if x != nil {
		return x.AuraCurValue
	}
	return 0
}

func (x *BedAuraState) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

// 床位封印状态
type BedSealState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSealed      bool                   `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"` // 是否被封印
	SealedAt      int64                  `protobuf:"varint,2,opt,name=sealed_at,json=sealedAt,proto3" json:"sealed_at,omitempty"` // 封印时间，用于计算融化进度
	MaxValue      int64                  `protobuf:"varint,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"` // 封印进度最大值
	CurValue      int64                  `protobuf:"varint,4,opt,name=cur_value,json=curValue,proto3" json:"cur_value,omitempty"` // 当前封印进度值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedSealState) Reset() {
	*x = BedSealState{}
	mi := &file_bed_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedSealState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedSealState) ProtoMessage() {}

func (x *BedSealState) ProtoReflect() protoreflect.Message {
	mi := &file_bed_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedSealState.ProtoReflect.Descriptor instead.
func (*BedSealState) Descriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{1}
}

func (x *BedSealState) GetIsSealed() bool {
	if x != nil {
		return x.IsSealed
	}
	return false
}

func (x *BedSealState) GetSealedAt() int64 {
	if x != nil {
		return x.SealedAt
	}
	return 0
}

func (x *BedSealState) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *BedSealState) GetCurValue() int64 {
	if x != nil {
		return x.CurValue
	}
	return 0
}

// 床位信息
type BedInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuraState     *BedAuraState          `protobuf:"bytes,1,opt,name=aura_state,json=auraState,proto3" json:"aura_state,omitempty"` // 灵气状态
	SealState     *BedSealState          `protobuf:"bytes,2,opt,name=seal_state,json=sealState,proto3" json:"seal_state,omitempty"` // 封印状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedInfo) Reset() {
	*x = BedInfo{}
	mi := &file_bed_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedInfo) ProtoMessage() {}

func (x *BedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bed_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedInfo.ProtoReflect.Descriptor instead.
func (*BedInfo) Descriptor() ([]byte, []int) {
	return file_bed_type_proto_rawDescGZIP(), []int{2}
}

func (x *BedInfo) GetAuraState() *BedAuraState {
	if x != nil {
		return x.AuraState
	}
	return nil
}

func (x *BedInfo) GetSealState() *BedSealState {
	if x != nil {
		return x.SealState
	}
	return nil
}

var File_bed_type_proto protoreflect.FileDescriptor

const file_bed_type_proto_rawDesc = "" +
	"\n" +
	"\x0ebed_type.proto\x12\x10zeus.game.bed.v1\"u\n" +
	"\fBedAuraState\x12$\n" +
	"\x0eaura_max_value\x18\x01 \x01(\x03R\fauraMaxValue\x12$\n" +
	"\x0eaura_cur_value\x18\x02 \x01(\x03R\fauraCurValue\x12\x19\n" +
	"\breset_at\x18\x03 \x01(\x03R\aresetAt\"\x82\x01\n" +
	"\fBedSealState\x12\x1b\n" +
	"\tis_sealed\x18\x01 \x01(\bR\bisSealed\x12\x1b\n" +
	"\tsealed_at\x18\x02 \x01(\x03R\bsealedAt\x12\x1b\n" +
	"\tmax_value\x18\x03 \x01(\x03R\bmaxValue\x12\x1b\n" +
	"\tcur_value\x18\x04 \x01(\x03R\bcurValue\"\x87\x01\n" +
	"\aBedInfo\x12=\n" +
	"\n" +
	"aura_state\x18\x01 \x01(\v2\x1e.zeus.game.bed.v1.BedAuraStateR\tauraState\x12=\n" +
	"\n" +
	"seal_state\x18\x02 \x01(\v2\x1e.zeus.game.bed.v1.BedSealStateR\tsealStateB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_bed_type_proto_rawDescOnce sync.Once
	file_bed_type_proto_rawDescData []byte
)

func file_bed_type_proto_rawDescGZIP() []byte {
	file_bed_type_proto_rawDescOnce.Do(func() {
		file_bed_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bed_type_proto_rawDesc), len(file_bed_type_proto_rawDesc)))
	})
	return file_bed_type_proto_rawDescData
}

var file_bed_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bed_type_proto_goTypes = []any{
	(*BedAuraState)(nil), // 0: zeus.game.bed.v1.BedAuraState
	(*BedSealState)(nil), // 1: zeus.game.bed.v1.BedSealState
	(*BedInfo)(nil),      // 2: zeus.game.bed.v1.BedInfo
}
var file_bed_type_proto_depIdxs = []int32{
	0, // 0: zeus.game.bed.v1.BedInfo.aura_state:type_name -> zeus.game.bed.v1.BedAuraState
	1, // 1: zeus.game.bed.v1.BedInfo.seal_state:type_name -> zeus.game.bed.v1.BedSealState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bed_type_proto_init() }
func file_bed_type_proto_init() {
	if File_bed_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bed_type_proto_rawDesc), len(file_bed_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bed_type_proto_goTypes,
		DependencyIndexes: file_bed_type_proto_depIdxs,
		MessageInfos:      file_bed_type_proto_msgTypes,
	}.Build()
	File_bed_type_proto = out.File
	file_bed_type_proto_goTypes = nil
	file_bed_type_proto_depIdxs = nil
}
