// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: competition.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 主播报名参加当前轮次竞赛
type CompetitionSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionSignupRequest) Reset() {
	*x = CompetitionSignupRequest{}
	mi := &file_competition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSignupRequest) ProtoMessage() {}

func (x *CompetitionSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSignupRequest.ProtoReflect.Descriptor instead.
func (*CompetitionSignupRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{0}
}

type CompetitionSignupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// 当前主播在全局报名榜中的数据（排名 / 得分等）
	Entry         *CompetitionRankEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionSignupResponse) Reset() {
	*x = CompetitionSignupResponse{}
	mi := &file_competition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSignupResponse) ProtoMessage() {}

func (x *CompetitionSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSignupResponse.ProtoReflect.Descriptor instead.
func (*CompetitionSignupResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{1}
}

func (x *CompetitionSignupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CompetitionSignupResponse) GetEntry() *CompetitionRankEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// 观众为当前直播间主播助力（消耗装饰能量）
type CompetitionSignupHelpRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DecorationEnergy int64                  `protobuf:"varint,1,opt,name=decoration_energy,json=decorationEnergy,proto3" json:"decoration_energy,omitempty"` // 本次消耗的装饰能量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompetitionSignupHelpRequest) Reset() {
	*x = CompetitionSignupHelpRequest{}
	mi := &file_competition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSignupHelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSignupHelpRequest) ProtoMessage() {}

func (x *CompetitionSignupHelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSignupHelpRequest.ProtoReflect.Descriptor instead.
func (*CompetitionSignupHelpRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{2}
}

func (x *CompetitionSignupHelpRequest) GetDecorationEnergy() int64 {
	if x != nil {
		return x.DecorationEnergy
	}
	return 0
}

type CompetitionSignupHelpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TotalEnergy   int64                  `protobuf:"varint,2,opt,name=total_energy,json=totalEnergy,proto3" json:"total_energy,omitempty"` // 当前直播间累计助力值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionSignupHelpResponse) Reset() {
	*x = CompetitionSignupHelpResponse{}
	mi := &file_competition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSignupHelpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSignupHelpResponse) ProtoMessage() {}

func (x *CompetitionSignupHelpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSignupHelpResponse.ProtoReflect.Descriptor instead.
func (*CompetitionSignupHelpResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{3}
}

func (x *CompetitionSignupHelpResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CompetitionSignupHelpResponse) GetTotalEnergy() int64 {
	if x != nil {
		return x.TotalEnergy
	}
	return 0
}

// 任意阶段：同步当前竞赛状态（用户进入直播间时下发）
type CompetitionStateSyncNotify struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	State         *CompetitionState       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                                // 当前轮次整体状态
	HistoryTop3   []*CompetitionRankEntry `protobuf:"bytes,2,rep,name=history_top3,json=historyTop3,proto3" json:"history_top3,omitempty"` // 历史前三（展示用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionStateSyncNotify) Reset() {
	*x = CompetitionStateSyncNotify{}
	mi := &file_competition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionStateSyncNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionStateSyncNotify) ProtoMessage() {}

func (x *CompetitionStateSyncNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionStateSyncNotify.ProtoReflect.Descriptor instead.
func (*CompetitionStateSyncNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{4}
}

func (x *CompetitionStateSyncNotify) GetState() *CompetitionState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CompetitionStateSyncNotify) GetHistoryTop3() []*CompetitionRankEntry {
	if x != nil {
		return x.HistoryTop3
	}
	return nil
}

// 全局报名排行榜更新（前 N 名），所有直播间展示同一份数据
type CompetitionSignupRankNotify struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Ranks         []*CompetitionRankEntry `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionSignupRankNotify) Reset() {
	*x = CompetitionSignupRankNotify{}
	mi := &file_competition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSignupRankNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSignupRankNotify) ProtoMessage() {}

func (x *CompetitionSignupRankNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSignupRankNotify.ProtoReflect.Descriptor instead.
func (*CompetitionSignupRankNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{5}
}

func (x *CompetitionSignupRankNotify) GetRanks() []*CompetitionRankEntry {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// 单个候选奖励（用于投票展示）
type CompetitionVoteCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      uint32                 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"` // 选项下标（0~5）
	Reward        *CompetitionReward     `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"`                      // 对应奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteCandidate) Reset() {
	*x = CompetitionVoteCandidate{}
	mi := &file_competition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteCandidate) ProtoMessage() {}

func (x *CompetitionVoteCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteCandidate.ProtoReflect.Descriptor instead.
func (*CompetitionVoteCandidate) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{6}
}

func (x *CompetitionVoteCandidate) GetOptionId() uint32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *CompetitionVoteCandidate) GetReward() *CompetitionReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

// 投票开始/候选列表同步
type CompetitionVoteStartNotify struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VoteEndTime   int64                       `protobuf:"varint,1,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"` // 投票结束时间戳（秒）
	Candidates    []*CompetitionVoteCandidate `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`                         // 候选奖励列表（含固定 + 随机）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteStartNotify) Reset() {
	*x = CompetitionVoteStartNotify{}
	mi := &file_competition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteStartNotify) ProtoMessage() {}

func (x *CompetitionVoteStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteStartNotify.ProtoReflect.Descriptor instead.
func (*CompetitionVoteStartNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{7}
}

func (x *CompetitionVoteStartNotify) GetVoteEndTime() int64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *CompetitionVoteStartNotify) GetCandidates() []*CompetitionVoteCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// 玩家为某奖励选项投票
type CompetitionVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      uint32                 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"` // 对应 CompetitionVoteCandidate.option_id
	Votes         uint32                 `protobuf:"varint,2,opt,name=votes,proto3" json:"votes,omitempty"`                       // 本次投出的票数（由金币等换算）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteRequest) Reset() {
	*x = CompetitionVoteRequest{}
	mi := &file_competition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteRequest) ProtoMessage() {}

func (x *CompetitionVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteRequest.ProtoReflect.Descriptor instead.
func (*CompetitionVoteRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{8}
}

func (x *CompetitionVoteRequest) GetOptionId() uint32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *CompetitionVoteRequest) GetVotes() uint32 {
	if x != nil {
		return x.Votes
	}
	return 0
}

type CompetitionVoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// 本次投票的选项及最新票数
	Option        *CompetitionVoteOption `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteResponse) Reset() {
	*x = CompetitionVoteResponse{}
	mi := &file_competition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteResponse) ProtoMessage() {}

func (x *CompetitionVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteResponse.ProtoReflect.Descriptor instead.
func (*CompetitionVoteResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{9}
}

func (x *CompetitionVoteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CompetitionVoteResponse) GetOption() *CompetitionVoteOption {
	if x != nil {
		return x.Option
	}
	return nil
}

// 投票进度通知（候选奖励的当前票数）
type CompetitionVoteProgressNotify struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Options       []*CompetitionVoteOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"` // option_id + vote_count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteProgressNotify) Reset() {
	*x = CompetitionVoteProgressNotify{}
	mi := &file_competition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteProgressNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteProgressNotify) ProtoMessage() {}

func (x *CompetitionVoteProgressNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteProgressNotify.ProtoReflect.Descriptor instead.
func (*CompetitionVoteProgressNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{10}
}

func (x *CompetitionVoteProgressNotify) GetOptions() []*CompetitionVoteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// 抢占擂台（使用当前装饰得分等内部逻辑，无需额外参数）
type CompetitionCaptureArenaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionCaptureArenaRequest) Reset() {
	*x = CompetitionCaptureArenaRequest{}
	mi := &file_competition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionCaptureArenaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionCaptureArenaRequest) ProtoMessage() {}

func (x *CompetitionCaptureArenaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionCaptureArenaRequest.ProtoReflect.Descriptor instead.
func (*CompetitionCaptureArenaRequest) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{11}
}

type CompetitionCaptureArenaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Arena         *CompetitionArenaInfo  `protobuf:"bytes,2,opt,name=arena,proto3" json:"arena,omitempty"` // 抢占后的最新擂台状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionCaptureArenaResponse) Reset() {
	*x = CompetitionCaptureArenaResponse{}
	mi := &file_competition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionCaptureArenaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionCaptureArenaResponse) ProtoMessage() {}

func (x *CompetitionCaptureArenaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionCaptureArenaResponse.ProtoReflect.Descriptor instead.
func (*CompetitionCaptureArenaResponse) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{12}
}

func (x *CompetitionCaptureArenaResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CompetitionCaptureArenaResponse) GetArena() *CompetitionArenaInfo {
	if x != nil {
		return x.Arena
	}
	return nil
}

// 擂台状态变更通知（有人抢到或被挤下）
type CompetitionArenaNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arena         *CompetitionArenaInfo  `protobuf:"bytes,1,opt,name=arena,proto3" json:"arena,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionArenaNotify) Reset() {
	*x = CompetitionArenaNotify{}
	mi := &file_competition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionArenaNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionArenaNotify) ProtoMessage() {}

func (x *CompetitionArenaNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionArenaNotify.ProtoReflect.Descriptor instead.
func (*CompetitionArenaNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{13}
}

func (x *CompetitionArenaNotify) GetArena() *CompetitionArenaInfo {
	if x != nil {
		return x.Arena
	}
	return nil
}

// 本轮结算通知（成功 / 失败界面）
type CompetitionSettleNotify struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Win    bool                   `protobuf:"varint,1,opt,name=win,proto3" json:"win,omitempty"`      // 当前直播间是否获胜
	Reward *CompetitionReward     `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"` // 获得的奖励
	Arena  *CompetitionArenaInfo  `protobuf:"bytes,3,opt,name=arena,proto3" json:"arena,omitempty"`   // 最终擂台状态
	// 本轮获胜直播间信息
	Winner *CompetitionWinnerInfo `protobuf:"bytes,4,opt,name=winner,proto3" json:"winner,omitempty"`
	// 历史竞赛获胜者列表（所有直播间共享）
	HistoryWinners []*CompetitionWinnerHistoryEntry `protobuf:"bytes,5,rep,name=history_winners,json=historyWinners,proto3" json:"history_winners,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompetitionSettleNotify) Reset() {
	*x = CompetitionSettleNotify{}
	mi := &file_competition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionSettleNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionSettleNotify) ProtoMessage() {}

func (x *CompetitionSettleNotify) ProtoReflect() protoreflect.Message {
	mi := &file_competition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionSettleNotify.ProtoReflect.Descriptor instead.
func (*CompetitionSettleNotify) Descriptor() ([]byte, []int) {
	return file_competition_proto_rawDescGZIP(), []int{14}
}

func (x *CompetitionSettleNotify) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *CompetitionSettleNotify) GetReward() *CompetitionReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *CompetitionSettleNotify) GetArena() *CompetitionArenaInfo {
	if x != nil {
		return x.Arena
	}
	return nil
}

func (x *CompetitionSettleNotify) GetWinner() *CompetitionWinnerInfo {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *CompetitionSettleNotify) GetHistoryWinners() []*CompetitionWinnerHistoryEntry {
	if x != nil {
		return x.HistoryWinners
	}
	return nil
}

var File_competition_proto protoreflect.FileDescriptor

const file_competition_proto_rawDesc = "" +
	"\n" +
	"\x11competition.proto\x12\x18zeus.game.competition.v1\x1a\x0eerr_code.proto\x1a\x16competition_type.proto\"\x1a\n" +
	"\x18CompetitionSignupRequest\"\x92\x01\n" +
	"\x19CompetitionSignupResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12D\n" +
	"\x05entry\x18\x02 \x01(\v2..zeus.game.competition.v1.CompetitionRankEntryR\x05entry\"K\n" +
	"\x1cCompetitionSignupHelpRequest\x12+\n" +
	"\x11decoration_energy\x18\x01 \x01(\x03R\x10decorationEnergy\"s\n" +
	"\x1dCompetitionSignupHelpResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12!\n" +
	"\ftotal_energy\x18\x02 \x01(\x03R\vtotalEnergy\"\xb1\x01\n" +
	"\x1aCompetitionStateSyncNotify\x12@\n" +
	"\x05state\x18\x01 \x01(\v2*.zeus.game.competition.v1.CompetitionStateR\x05state\x12Q\n" +
	"\fhistory_top3\x18\x02 \x03(\v2..zeus.game.competition.v1.CompetitionRankEntryR\vhistoryTop3\"c\n" +
	"\x1bCompetitionSignupRankNotify\x12D\n" +
	"\x05ranks\x18\x01 \x03(\v2..zeus.game.competition.v1.CompetitionRankEntryR\x05ranks\"|\n" +
	"\x18CompetitionVoteCandidate\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\rR\boptionId\x12C\n" +
	"\x06reward\x18\x02 \x01(\v2+.zeus.game.competition.v1.CompetitionRewardR\x06reward\"\x94\x01\n" +
	"\x1aCompetitionVoteStartNotify\x12\"\n" +
	"\rvote_end_time\x18\x01 \x01(\x03R\vvoteEndTime\x12R\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v22.zeus.game.competition.v1.CompetitionVoteCandidateR\n" +
	"candidates\"K\n" +
	"\x16CompetitionVoteRequest\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\rR\boptionId\x12\x14\n" +
	"\x05votes\x18\x02 \x01(\rR\x05votes\"\x93\x01\n" +
	"\x17CompetitionVoteResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12G\n" +
	"\x06option\x18\x02 \x01(\v2/.zeus.game.competition.v1.CompetitionVoteOptionR\x06option\"j\n" +
	"\x1dCompetitionVoteProgressNotify\x12I\n" +
	"\aoptions\x18\x01 \x03(\v2/.zeus.game.competition.v1.CompetitionVoteOptionR\aoptions\" \n" +
	"\x1eCompetitionCaptureArenaRequest\"\x98\x01\n" +
	"\x1fCompetitionCaptureArenaResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12D\n" +
	"\x05arena\x18\x02 \x01(\v2..zeus.game.competition.v1.CompetitionArenaInfoR\x05arena\"^\n" +
	"\x16CompetitionArenaNotify\x12D\n" +
	"\x05arena\x18\x01 \x01(\v2..zeus.game.competition.v1.CompetitionArenaInfoR\x05arena\"\xe1\x02\n" +
	"\x17CompetitionSettleNotify\x12\x10\n" +
	"\x03win\x18\x01 \x01(\bR\x03win\x12C\n" +
	"\x06reward\x18\x02 \x01(\v2+.zeus.game.competition.v1.CompetitionRewardR\x06reward\x12D\n" +
	"\x05arena\x18\x03 \x01(\v2..zeus.game.competition.v1.CompetitionArenaInfoR\x05arena\x12G\n" +
	"\x06winner\x18\x04 \x01(\v2/.zeus.game.competition.v1.CompetitionWinnerInfoR\x06winner\x12`\n" +
	"\x0fhistory_winners\x18\x05 \x03(\v27.zeus.game.competition.v1.CompetitionWinnerHistoryEntryR\x0ehistoryWinnersB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_competition_proto_rawDescOnce sync.Once
	file_competition_proto_rawDescData []byte
)

func file_competition_proto_rawDescGZIP() []byte {
	file_competition_proto_rawDescOnce.Do(func() {
		file_competition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_competition_proto_rawDesc), len(file_competition_proto_rawDesc)))
	})
	return file_competition_proto_rawDescData
}

var file_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_competition_proto_goTypes = []any{
	(*CompetitionSignupRequest)(nil),        // 0: zeus.game.competition.v1.CompetitionSignupRequest
	(*CompetitionSignupResponse)(nil),       // 1: zeus.game.competition.v1.CompetitionSignupResponse
	(*CompetitionSignupHelpRequest)(nil),    // 2: zeus.game.competition.v1.CompetitionSignupHelpRequest
	(*CompetitionSignupHelpResponse)(nil),   // 3: zeus.game.competition.v1.CompetitionSignupHelpResponse
	(*CompetitionStateSyncNotify)(nil),      // 4: zeus.game.competition.v1.CompetitionStateSyncNotify
	(*CompetitionSignupRankNotify)(nil),     // 5: zeus.game.competition.v1.CompetitionSignupRankNotify
	(*CompetitionVoteCandidate)(nil),        // 6: zeus.game.competition.v1.CompetitionVoteCandidate
	(*CompetitionVoteStartNotify)(nil),      // 7: zeus.game.competition.v1.CompetitionVoteStartNotify
	(*CompetitionVoteRequest)(nil),          // 8: zeus.game.competition.v1.CompetitionVoteRequest
	(*CompetitionVoteResponse)(nil),         // 9: zeus.game.competition.v1.CompetitionVoteResponse
	(*CompetitionVoteProgressNotify)(nil),   // 10: zeus.game.competition.v1.CompetitionVoteProgressNotify
	(*CompetitionCaptureArenaRequest)(nil),  // 11: zeus.game.competition.v1.CompetitionCaptureArenaRequest
	(*CompetitionCaptureArenaResponse)(nil), // 12: zeus.game.competition.v1.CompetitionCaptureArenaResponse
	(*CompetitionArenaNotify)(nil),          // 13: zeus.game.competition.v1.CompetitionArenaNotify
	(*CompetitionSettleNotify)(nil),         // 14: zeus.game.competition.v1.CompetitionSettleNotify
	(*Error)(nil),                           // 15: zeus.game.error.v1.Error
	(*CompetitionRankEntry)(nil),            // 16: zeus.game.competition.v1.CompetitionRankEntry
	(*CompetitionState)(nil),                // 17: zeus.game.competition.v1.CompetitionState
	(*CompetitionReward)(nil),               // 18: zeus.game.competition.v1.CompetitionReward
	(*CompetitionVoteOption)(nil),           // 19: zeus.game.competition.v1.CompetitionVoteOption
	(*CompetitionArenaInfo)(nil),            // 20: zeus.game.competition.v1.CompetitionArenaInfo
	(*CompetitionWinnerInfo)(nil),           // 21: zeus.game.competition.v1.CompetitionWinnerInfo
	(*CompetitionWinnerHistoryEntry)(nil),   // 22: zeus.game.competition.v1.CompetitionWinnerHistoryEntry
}
var file_competition_proto_depIdxs = []int32{
	15, // 0: zeus.game.competition.v1.CompetitionSignupResponse.error:type_name -> zeus.game.error.v1.Error
	16, // 1: zeus.game.competition.v1.CompetitionSignupResponse.entry:type_name -> zeus.game.competition.v1.CompetitionRankEntry
	15, // 2: zeus.game.competition.v1.CompetitionSignupHelpResponse.error:type_name -> zeus.game.error.v1.Error
	17, // 3: zeus.game.competition.v1.CompetitionStateSyncNotify.state:type_name -> zeus.game.competition.v1.CompetitionState
	16, // 4: zeus.game.competition.v1.CompetitionStateSyncNotify.history_top3:type_name -> zeus.game.competition.v1.CompetitionRankEntry
	16, // 5: zeus.game.competition.v1.CompetitionSignupRankNotify.ranks:type_name -> zeus.game.competition.v1.CompetitionRankEntry
	18, // 6: zeus.game.competition.v1.CompetitionVoteCandidate.reward:type_name -> zeus.game.competition.v1.CompetitionReward
	6,  // 7: zeus.game.competition.v1.CompetitionVoteStartNotify.candidates:type_name -> zeus.game.competition.v1.CompetitionVoteCandidate
	15, // 8: zeus.game.competition.v1.CompetitionVoteResponse.error:type_name -> zeus.game.error.v1.Error
	19, // 9: zeus.game.competition.v1.CompetitionVoteResponse.option:type_name -> zeus.game.competition.v1.CompetitionVoteOption
	19, // 10: zeus.game.competition.v1.CompetitionVoteProgressNotify.options:type_name -> zeus.game.competition.v1.CompetitionVoteOption
	15, // 11: zeus.game.competition.v1.CompetitionCaptureArenaResponse.error:type_name -> zeus.game.error.v1.Error
	20, // 12: zeus.game.competition.v1.CompetitionCaptureArenaResponse.arena:type_name -> zeus.game.competition.v1.CompetitionArenaInfo
	20, // 13: zeus.game.competition.v1.CompetitionArenaNotify.arena:type_name -> zeus.game.competition.v1.CompetitionArenaInfo
	18, // 14: zeus.game.competition.v1.CompetitionSettleNotify.reward:type_name -> zeus.game.competition.v1.CompetitionReward
	20, // 15: zeus.game.competition.v1.CompetitionSettleNotify.arena:type_name -> zeus.game.competition.v1.CompetitionArenaInfo
	21, // 16: zeus.game.competition.v1.CompetitionSettleNotify.winner:type_name -> zeus.game.competition.v1.CompetitionWinnerInfo
	22, // 17: zeus.game.competition.v1.CompetitionSettleNotify.history_winners:type_name -> zeus.game.competition.v1.CompetitionWinnerHistoryEntry
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_competition_proto_init() }
func file_competition_proto_init() {
	if File_competition_proto != nil {
		return
	}
	file_err_code_proto_init()
	file_competition_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_competition_proto_rawDesc), len(file_competition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_competition_proto_goTypes,
		DependencyIndexes: file_competition_proto_depIdxs,
		MessageInfos:      file_competition_proto_msgTypes,
	}.Build()
	File_competition_proto = out.File
	file_competition_proto_goTypes = nil
	file_competition_proto_depIdxs = nil
}
