// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: competition_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 竞赛阶段
type CompetitionPhase int32

const (
	CompetitionPhase_COMPETITION_PHASE_UNKNOWN CompetitionPhase = 0
	CompetitionPhase_COMPETITION_PHASE_SIGNUP  CompetitionPhase = 1 // 报名阶段
	CompetitionPhase_COMPETITION_PHASE_VOTE    CompetitionPhase = 2 // 投票阶段
	CompetitionPhase_COMPETITION_PHASE_BATTLE  CompetitionPhase = 3 // 竞赛阶段
	CompetitionPhase_COMPETITION_PHASE_SETTLE  CompetitionPhase = 4 // 结算阶段
)

// Enum value maps for CompetitionPhase.
var (
	CompetitionPhase_name = map[int32]string{
		0: "COMPETITION_PHASE_UNKNOWN",
		1: "COMPETITION_PHASE_SIGNUP",
		2: "COMPETITION_PHASE_VOTE",
		3: "COMPETITION_PHASE_BATTLE",
		4: "COMPETITION_PHASE_SETTLE",
	}
	CompetitionPhase_value = map[string]int32{
		"COMPETITION_PHASE_UNKNOWN": 0,
		"COMPETITION_PHASE_SIGNUP":  1,
		"COMPETITION_PHASE_VOTE":    2,
		"COMPETITION_PHASE_BATTLE":  3,
		"COMPETITION_PHASE_SETTLE":  4,
	}
)

func (x CompetitionPhase) Enum() *CompetitionPhase {
	p := new(CompetitionPhase)
	*p = x
	return p
}

func (x CompetitionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompetitionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_competition_type_proto_enumTypes[0].Descriptor()
}

func (CompetitionPhase) Type() protoreflect.EnumType {
	return &file_competition_type_proto_enumTypes[0]
}

func (x CompetitionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompetitionPhase.Descriptor instead.
func (CompetitionPhase) EnumDescriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{0}
}

// 竞赛奖励（道具 + 数量）
type CompetitionReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCfgId     uint32                 `protobuf:"varint,1,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` // 奖励道具配置 ID
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                          // 奖励数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionReward) Reset() {
	*x = CompetitionReward{}
	mi := &file_competition_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionReward) ProtoMessage() {}

func (x *CompetitionReward) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionReward.ProtoReflect.Descriptor instead.
func (*CompetitionReward) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{0}
}

func (x *CompetitionReward) GetItemCfgId() uint32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *CompetitionReward) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 投票选项
type CompetitionVoteOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 选项 ID：对应当前候选奖励列表中的下标（例如 0~5）
	OptionId      uint32 `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	VoteCount     uint64 `protobuf:"varint,2,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"` // 当前累计票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionVoteOption) Reset() {
	*x = CompetitionVoteOption{}
	mi := &file_competition_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionVoteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionVoteOption) ProtoMessage() {}

func (x *CompetitionVoteOption) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionVoteOption.ProtoReflect.Descriptor instead.
func (*CompetitionVoteOption) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{1}
}

func (x *CompetitionVoteOption) GetOptionId() uint32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *CompetitionVoteOption) GetVoteCount() uint64 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// 报名 / 助力榜条目（前 10、历史前三等）
type CompetitionRankEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint32                 `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`                         // 排名
	AnchorId      uint64                 `protobuf:"varint,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"` // 主播 ID
	RoomId        uint64                 `protobuf:"varint,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`       // 直播间 ID
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                       // 助力得分（例如消耗的装饰能量）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionRankEntry) Reset() {
	*x = CompetitionRankEntry{}
	mi := &file_competition_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionRankEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionRankEntry) ProtoMessage() {}

func (x *CompetitionRankEntry) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionRankEntry.ProtoReflect.Descriptor instead.
func (*CompetitionRankEntry) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{2}
}

func (x *CompetitionRankEntry) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CompetitionRankEntry) GetAnchorId() uint64 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *CompetitionRankEntry) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CompetitionRankEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 当前擂台占领信息
type CompetitionArenaInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                           // 擂台所属直播间
	HolderPlayerId uint64                 `protobuf:"varint,2,opt,name=holder_player_id,json=holderPlayerId,proto3" json:"holder_player_id,omitempty"` // 当前擂台玩家 ID，0 表示无人
	Holder         *BaseRoleInfo          `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`                                          // 当前擂主角色信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompetitionArenaInfo) Reset() {
	*x = CompetitionArenaInfo{}
	mi := &file_competition_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionArenaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionArenaInfo) ProtoMessage() {}

func (x *CompetitionArenaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionArenaInfo.ProtoReflect.Descriptor instead.
func (*CompetitionArenaInfo) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{3}
}

func (x *CompetitionArenaInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CompetitionArenaInfo) GetHolderPlayerId() uint64 {
	if x != nil {
		return x.HolderPlayerId
	}
	return 0
}

func (x *CompetitionArenaInfo) GetHolder() *BaseRoleInfo {
	if x != nil {
		return x.Holder
	}
	return nil
}

// 本轮获胜者信息
type CompetitionWinnerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`            // 获胜直播间 ID
	AnchorId      uint64                 `protobuf:"varint,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`      // 获胜主播 ID
	AnchorName    string                 `protobuf:"bytes,3,opt,name=anchor_name,json=anchorName,proto3" json:"anchor_name,omitempty"` // 获胜主播名称
	AvatarId      uint64                 `protobuf:"varint,4,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`      // 获胜主播头像 ID
	VoteCount     uint64                 `protobuf:"varint,5,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`   // 本轮获得的总票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionWinnerInfo) Reset() {
	*x = CompetitionWinnerInfo{}
	mi := &file_competition_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionWinnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionWinnerInfo) ProtoMessage() {}

func (x *CompetitionWinnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionWinnerInfo.ProtoReflect.Descriptor instead.
func (*CompetitionWinnerInfo) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{4}
}

func (x *CompetitionWinnerInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CompetitionWinnerInfo) GetAnchorId() uint64 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *CompetitionWinnerInfo) GetAnchorName() string {
	if x != nil {
		return x.AnchorName
	}
	return ""
}

func (x *CompetitionWinnerInfo) GetAvatarId() uint64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *CompetitionWinnerInfo) GetVoteCount() uint64 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// 历史获胜者信息（用于历史竞赛获胜者列表）
type CompetitionWinnerHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnchorId      uint64                 `protobuf:"varint,1,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`      // 主播 ID
	AnchorName    string                 `protobuf:"bytes,2,opt,name=anchor_name,json=anchorName,proto3" json:"anchor_name,omitempty"` // 主播名称
	AvatarId      uint64                 `protobuf:"varint,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`      // 主播头像 ID
	VoteCount     uint64                 `protobuf:"varint,4,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`   // 当轮获得的票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionWinnerHistoryEntry) Reset() {
	*x = CompetitionWinnerHistoryEntry{}
	mi := &file_competition_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionWinnerHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionWinnerHistoryEntry) ProtoMessage() {}

func (x *CompetitionWinnerHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionWinnerHistoryEntry.ProtoReflect.Descriptor instead.
func (*CompetitionWinnerHistoryEntry) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{5}
}

func (x *CompetitionWinnerHistoryEntry) GetAnchorId() uint64 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *CompetitionWinnerHistoryEntry) GetAnchorName() string {
	if x != nil {
		return x.AnchorName
	}
	return ""
}

func (x *CompetitionWinnerHistoryEntry) GetAvatarId() uint64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *CompetitionWinnerHistoryEntry) GetVoteCount() uint64 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// 当前竞赛的整体状态
type CompetitionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         CompetitionPhase       `protobuf:"varint,1,opt,name=phase,proto3,enum=zeus.game.competition.v1.CompetitionPhase" json:"phase,omitempty"` // 当前阶段
	PhaseEndTime  int64                  `protobuf:"varint,2,opt,name=phase_end_time,json=phaseEndTime,proto3" json:"phase_end_time,omitempty"`            // 当前阶段结束时间戳（秒）
	Arena         *CompetitionArenaInfo  `protobuf:"bytes,3,opt,name=arena,proto3" json:"arena,omitempty"`                                                 // 当前擂台状态
	Reward        *CompetitionReward     `protobuf:"bytes,4,opt,name=reward,proto3" json:"reward,omitempty"`                                               // 当前竞赛奖励
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetitionState) Reset() {
	*x = CompetitionState{}
	mi := &file_competition_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetitionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetitionState) ProtoMessage() {}

func (x *CompetitionState) ProtoReflect() protoreflect.Message {
	mi := &file_competition_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetitionState.ProtoReflect.Descriptor instead.
func (*CompetitionState) Descriptor() ([]byte, []int) {
	return file_competition_type_proto_rawDescGZIP(), []int{6}
}

func (x *CompetitionState) GetPhase() CompetitionPhase {
	if x != nil {
		return x.Phase
	}
	return CompetitionPhase_COMPETITION_PHASE_UNKNOWN
}

func (x *CompetitionState) GetPhaseEndTime() int64 {
	if x != nil {
		return x.PhaseEndTime
	}
	return 0
}

func (x *CompetitionState) GetArena() *CompetitionArenaInfo {
	if x != nil {
		return x.Arena
	}
	return nil
}

func (x *CompetitionState) GetReward() *CompetitionReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

var File_competition_type_proto protoreflect.FileDescriptor

const file_competition_type_proto_rawDesc = "" +
	"\n" +
	"\x16competition_type.proto\x12\x18zeus.game.competition.v1\x1a\x0frole_type.proto\"K\n" +
	"\x11CompetitionReward\x12\x1e\n" +
	"\vitem_cfg_id\x18\x01 \x01(\rR\titemCfgId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\"S\n" +
	"\x15CompetitionVoteOption\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\rR\boptionId\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x02 \x01(\x04R\tvoteCount\"v\n" +
	"\x14CompetitionRankEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\rR\x04rank\x12\x1b\n" +
	"\tanchor_id\x18\x02 \x01(\x04R\banchorId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\x04R\x06roomId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\"\x92\x01\n" +
	"\x14CompetitionArenaInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12(\n" +
	"\x10holder_player_id\x18\x02 \x01(\x04R\x0eholderPlayerId\x127\n" +
	"\x06holder\x18\x03 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x06holder\"\xaa\x01\n" +
	"\x15CompetitionWinnerInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12\x1b\n" +
	"\tanchor_id\x18\x02 \x01(\x04R\banchorId\x12\x1f\n" +
	"\vanchor_name\x18\x03 \x01(\tR\n" +
	"anchorName\x12\x1b\n" +
	"\tavatar_id\x18\x04 \x01(\x04R\bavatarId\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x05 \x01(\x04R\tvoteCount\"\x99\x01\n" +
	"\x1dCompetitionWinnerHistoryEntry\x12\x1b\n" +
	"\tanchor_id\x18\x01 \x01(\x04R\banchorId\x12\x1f\n" +
	"\vanchor_name\x18\x02 \x01(\tR\n" +
	"anchorName\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\x04R\bavatarId\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x04 \x01(\x04R\tvoteCount\"\x85\x02\n" +
	"\x10CompetitionState\x12@\n" +
	"\x05phase\x18\x01 \x01(\x0e2*.zeus.game.competition.v1.CompetitionPhaseR\x05phase\x12$\n" +
	"\x0ephase_end_time\x18\x02 \x01(\x03R\fphaseEndTime\x12D\n" +
	"\x05arena\x18\x03 \x01(\v2..zeus.game.competition.v1.CompetitionArenaInfoR\x05arena\x12C\n" +
	"\x06reward\x18\x04 \x01(\v2+.zeus.game.competition.v1.CompetitionRewardR\x06reward*\xa7\x01\n" +
	"\x10CompetitionPhase\x12\x1d\n" +
	"\x19COMPETITION_PHASE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18COMPETITION_PHASE_SIGNUP\x10\x01\x12\x1a\n" +
	"\x16COMPETITION_PHASE_VOTE\x10\x02\x12\x1c\n" +
	"\x18COMPETITION_PHASE_BATTLE\x10\x03\x12\x1c\n" +
	"\x18COMPETITION_PHASE_SETTLE\x10\x04B<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_competition_type_proto_rawDescOnce sync.Once
	file_competition_type_proto_rawDescData []byte
)

func file_competition_type_proto_rawDescGZIP() []byte {
	file_competition_type_proto_rawDescOnce.Do(func() {
		file_competition_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_competition_type_proto_rawDesc), len(file_competition_type_proto_rawDesc)))
	})
	return file_competition_type_proto_rawDescData
}

var file_competition_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_competition_type_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_competition_type_proto_goTypes = []any{
	(CompetitionPhase)(0),                 // 0: zeus.game.competition.v1.CompetitionPhase
	(*CompetitionReward)(nil),             // 1: zeus.game.competition.v1.CompetitionReward
	(*CompetitionVoteOption)(nil),         // 2: zeus.game.competition.v1.CompetitionVoteOption
	(*CompetitionRankEntry)(nil),          // 3: zeus.game.competition.v1.CompetitionRankEntry
	(*CompetitionArenaInfo)(nil),          // 4: zeus.game.competition.v1.CompetitionArenaInfo
	(*CompetitionWinnerInfo)(nil),         // 5: zeus.game.competition.v1.CompetitionWinnerInfo
	(*CompetitionWinnerHistoryEntry)(nil), // 6: zeus.game.competition.v1.CompetitionWinnerHistoryEntry
	(*CompetitionState)(nil),              // 7: zeus.game.competition.v1.CompetitionState
	(*BaseRoleInfo)(nil),                  // 8: zeus.game.role.v1.BaseRoleInfo
}
var file_competition_type_proto_depIdxs = []int32{
	8, // 0: zeus.game.competition.v1.CompetitionArenaInfo.holder:type_name -> zeus.game.role.v1.BaseRoleInfo
	0, // 1: zeus.game.competition.v1.CompetitionState.phase:type_name -> zeus.game.competition.v1.CompetitionPhase
	4, // 2: zeus.game.competition.v1.CompetitionState.arena:type_name -> zeus.game.competition.v1.CompetitionArenaInfo
	1, // 3: zeus.game.competition.v1.CompetitionState.reward:type_name -> zeus.game.competition.v1.CompetitionReward
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_competition_type_proto_init() }
func file_competition_type_proto_init() {
	if File_competition_type_proto != nil {
		return
	}
	file_role_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_competition_type_proto_rawDesc), len(file_competition_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_competition_type_proto_goTypes,
		DependencyIndexes: file_competition_type_proto_depIdxs,
		EnumInfos:         file_competition_type_proto_enumTypes,
		MessageInfos:      file_competition_type_proto_msgTypes,
	}.Build()
	File_competition_type_proto = out.File
	file_competition_type_proto_goTypes = nil
	file_competition_type_proto_depIdxs = nil
}
