// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: drop_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个掉落项
type DropEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ItemCfgId   uint32                 `protobuf:"varint,1,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` // 掉落的道具配置 ID
	Probability float32                `protobuf:"fixed32,2,opt,name=probability,proto3" json:"probability,omitempty"`               // 在本掉落列表中的抽中概率（0~1）
	// 掉落数量（可为区间）
	MinAmount     uint32 `protobuf:"varint,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"` // 最小数量
	MaxAmount     uint32 `protobuf:"varint,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"` // 最大数量（=min_amount 表示固定数量）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropEntry) Reset() {
	*x = DropEntry{}
	mi := &file_drop_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropEntry) ProtoMessage() {}

func (x *DropEntry) ProtoReflect() protoreflect.Message {
	mi := &file_drop_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropEntry.ProtoReflect.Descriptor instead.
func (*DropEntry) Descriptor() ([]byte, []int) {
	return file_drop_type_proto_rawDescGZIP(), []int{0}
}

func (x *DropEntry) GetItemCfgId() uint32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *DropEntry) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *DropEntry) GetMinAmount() uint32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *DropEntry) GetMaxAmount() uint32 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

// 掉落列表（奖池）
type DropList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DropListId    uint32                 `protobuf:"varint,1,opt,name=drop_list_id,json=dropListId,proto3" json:"drop_list_id,omitempty"` // 掉落列表 ID（配置用）
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`                             // 该列表在多个列表之间被选中的权重
	Entries       []*DropEntry           `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`                            // 本列表中的所有掉落项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropList) Reset() {
	*x = DropList{}
	mi := &file_drop_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropList) ProtoMessage() {}

func (x *DropList) ProtoReflect() protoreflect.Message {
	mi := &file_drop_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropList.ProtoReflect.Descriptor instead.
func (*DropList) Descriptor() ([]byte, []int) {
	return file_drop_type_proto_rawDescGZIP(), []int{1}
}

func (x *DropList) GetDropListId() uint32 {
	if x != nil {
		return x.DropListId
	}
	return 0
}

func (x *DropList) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DropList) GetEntries() []*DropEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_drop_type_proto protoreflect.FileDescriptor

const file_drop_type_proto_rawDesc = "" +
	"\n" +
	"\x0fdrop_type.proto\x12\x11zeus.game.drop.v1\"\x8b\x01\n" +
	"\tDropEntry\x12\x1e\n" +
	"\vitem_cfg_id\x18\x01 \x01(\rR\titemCfgId\x12 \n" +
	"\vprobability\x18\x02 \x01(\x02R\vprobability\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x03 \x01(\rR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\rR\tmaxAmount\"|\n" +
	"\bDropList\x12 \n" +
	"\fdrop_list_id\x18\x01 \x01(\rR\n" +
	"dropListId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x126\n" +
	"\aentries\x18\x03 \x03(\v2\x1c.zeus.game.drop.v1.DropEntryR\aentriesB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_drop_type_proto_rawDescOnce sync.Once
	file_drop_type_proto_rawDescData []byte
)

func file_drop_type_proto_rawDescGZIP() []byte {
	file_drop_type_proto_rawDescOnce.Do(func() {
		file_drop_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drop_type_proto_rawDesc), len(file_drop_type_proto_rawDesc)))
	})
	return file_drop_type_proto_rawDescData
}

var file_drop_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_drop_type_proto_goTypes = []any{
	(*DropEntry)(nil), // 0: zeus.game.drop.v1.DropEntry
	(*DropList)(nil),  // 1: zeus.game.drop.v1.DropList
}
var file_drop_type_proto_depIdxs = []int32{
	0, // 0: zeus.game.drop.v1.DropList.entries:type_name -> zeus.game.drop.v1.DropEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_drop_type_proto_init() }
func file_drop_type_proto_init() {
	if File_drop_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drop_type_proto_rawDesc), len(file_drop_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drop_type_proto_goTypes,
		DependencyIndexes: file_drop_type_proto_depIdxs,
		MessageInfos:      file_drop_type_proto_msgTypes,
	}.Build()
	File_drop_type_proto = out.File
	file_drop_type_proto_goTypes = nil
	file_drop_type_proto_depIdxs = nil
}
