// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: err_code.proto

// 游戏通用错误码

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 所有模块共用的错误码定义
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_SUCCESS ErrorCode = 0 // 成功
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_SUCCESS",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_SUCCESS": 0,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_err_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_err_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_err_code_proto_rawDescGZIP(), []int{0}
}

// 统一的错误返回结构
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=zeus.game.error.v1.ErrorCode" json:"code,omitempty"`
	// 人类可读的错误描述
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_err_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_err_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_err_code_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_SUCCESS
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_err_code_proto protoreflect.FileDescriptor

const file_err_code_proto_rawDesc = "" +
	"\n" +
	"\x0eerr_code.proto\x12\x12zeus.game.error.v1\"R\n" +
	"\x05Error\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.zeus.game.error.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*#\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_SUCCESS\x10\x00B<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_err_code_proto_rawDescOnce sync.Once
	file_err_code_proto_rawDescData []byte
)

func file_err_code_proto_rawDescGZIP() []byte {
	file_err_code_proto_rawDescOnce.Do(func() {
		file_err_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)))
	})
	return file_err_code_proto_rawDescData
}

var file_err_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_err_code_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_err_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: zeus.game.error.v1.ErrorCode
	(*Error)(nil),  // 1: zeus.game.error.v1.Error
}
var file_err_code_proto_depIdxs = []int32{
	0, // 0: zeus.game.error.v1.Error.code:type_name -> zeus.game.error.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_err_code_proto_init() }
func file_err_code_proto_init() {
	if File_err_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_err_code_proto_rawDesc), len(file_err_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_err_code_proto_goTypes,
		DependencyIndexes: file_err_code_proto_depIdxs,
		EnumInfos:         file_err_code_proto_enumTypes,
		MessageInfos:      file_err_code_proto_msgTypes,
	}.Build()
	File_err_code_proto = out.File
	file_err_code_proto_goTypes = nil
	file_err_code_proto_depIdxs = nil
}
