// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: farm.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取水果收购赔率配置 - 请求
type FruitAcquireInfoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitAcquireInfoListRequest) Reset() {
	*x = FruitAcquireInfoListRequest{}
	mi := &file_farm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitAcquireInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitAcquireInfoListRequest) ProtoMessage() {}

func (x *FruitAcquireInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitAcquireInfoListRequest.ProtoReflect.Descriptor instead.
func (*FruitAcquireInfoListRequest) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{0}
}

// 获取水果收购赔率配置 - 响应
type FruitAcquireInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *FruitAcquireInfoList  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitAcquireInfoListResponse) Reset() {
	*x = FruitAcquireInfoListResponse{}
	mi := &file_farm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitAcquireInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitAcquireInfoListResponse) ProtoMessage() {}

func (x *FruitAcquireInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitAcquireInfoListResponse.ProtoReflect.Descriptor instead.
func (*FruitAcquireInfoListResponse) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{1}
}

func (x *FruitAcquireInfoListResponse) GetList() *FruitAcquireInfoList {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取玩家田地信息列表 - 请求
type FarmLandInfoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmLandInfoListRequest) Reset() {
	*x = FarmLandInfoListRequest{}
	mi := &file_farm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmLandInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmLandInfoListRequest) ProtoMessage() {}

func (x *FarmLandInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmLandInfoListRequest.ProtoReflect.Descriptor instead.
func (*FarmLandInfoListRequest) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{2}
}

// 获取玩家田地信息列表 - 响应
type FarmLandInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandList      *FarmLandInfoList      `protobuf:"bytes,1,opt,name=land_list,json=landList,proto3" json:"land_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmLandInfoListResponse) Reset() {
	*x = FarmLandInfoListResponse{}
	mi := &file_farm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmLandInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmLandInfoListResponse) ProtoMessage() {}

func (x *FarmLandInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmLandInfoListResponse.ProtoReflect.Descriptor instead.
func (*FarmLandInfoListResponse) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{3}
}

func (x *FarmLandInfoListResponse) GetLandList() *FarmLandInfoList {
	if x != nil {
		return x.LandList
	}
	return nil
}

// 在指定田地种植作物 - 请求
type PlantFarmLandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandId        uint32                 `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`            // 田地编号
	ItemCfgId     uint32                 `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` // 种子道具配置 id
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // 种植数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantFarmLandRequest) Reset() {
	*x = PlantFarmLandRequest{}
	mi := &file_farm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantFarmLandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantFarmLandRequest) ProtoMessage() {}

func (x *PlantFarmLandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantFarmLandRequest.ProtoReflect.Descriptor instead.
func (*PlantFarmLandRequest) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{4}
}

func (x *PlantFarmLandRequest) GetLandId() uint32 {
	if x != nil {
		return x.LandId
	}
	return 0
}

func (x *PlantFarmLandRequest) GetItemCfgId() uint32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *PlantFarmLandRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 在指定田地种植作物 - 响应
type PlantFarmLandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	LandInfo      *FarmLandInfo          `protobuf:"bytes,2,opt,name=land_info,json=landInfo,proto3" json:"land_info,omitempty"` // 最新田地状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlantFarmLandResponse) Reset() {
	*x = PlantFarmLandResponse{}
	mi := &file_farm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlantFarmLandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantFarmLandResponse) ProtoMessage() {}

func (x *PlantFarmLandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_farm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantFarmLandResponse.ProtoReflect.Descriptor instead.
func (*PlantFarmLandResponse) Descriptor() ([]byte, []int) {
	return file_farm_proto_rawDescGZIP(), []int{5}
}

func (x *PlantFarmLandResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PlantFarmLandResponse) GetLandInfo() *FarmLandInfo {
	if x != nil {
		return x.LandInfo
	}
	return nil
}

var File_farm_proto protoreflect.FileDescriptor

const file_farm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"farm.proto\x12\x11zeus.game.farm.v1\x1a\x0eerr_code.proto\x1a\x0ffarm_type.proto\"\x1d\n" +
	"\x1bFruitAcquireInfoListRequest\"[\n" +
	"\x1cFruitAcquireInfoListResponse\x12;\n" +
	"\x04list\x18\x01 \x01(\v2'.zeus.game.farm.v1.FruitAcquireInfoListR\x04list\"\x19\n" +
	"\x17FarmLandInfoListRequest\"\\\n" +
	"\x18FarmLandInfoListResponse\x12@\n" +
	"\tland_list\x18\x01 \x01(\v2#.zeus.game.farm.v1.FarmLandInfoListR\blandList\"g\n" +
	"\x14PlantFarmLandRequest\x12\x17\n" +
	"\aland_id\x18\x01 \x01(\rR\x06landId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\rR\titemCfgId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\"\x86\x01\n" +
	"\x15PlantFarmLandResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12<\n" +
	"\tland_info\x18\x02 \x01(\v2\x1f.zeus.game.farm.v1.FarmLandInfoR\blandInfoB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_farm_proto_rawDescOnce sync.Once
	file_farm_proto_rawDescData []byte
)

func file_farm_proto_rawDescGZIP() []byte {
	file_farm_proto_rawDescOnce.Do(func() {
		file_farm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farm_proto_rawDesc), len(file_farm_proto_rawDesc)))
	})
	return file_farm_proto_rawDescData
}

var file_farm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_farm_proto_goTypes = []any{
	(*FruitAcquireInfoListRequest)(nil),  // 0: zeus.game.farm.v1.FruitAcquireInfoListRequest
	(*FruitAcquireInfoListResponse)(nil), // 1: zeus.game.farm.v1.FruitAcquireInfoListResponse
	(*FarmLandInfoListRequest)(nil),      // 2: zeus.game.farm.v1.FarmLandInfoListRequest
	(*FarmLandInfoListResponse)(nil),     // 3: zeus.game.farm.v1.FarmLandInfoListResponse
	(*PlantFarmLandRequest)(nil),         // 4: zeus.game.farm.v1.PlantFarmLandRequest
	(*PlantFarmLandResponse)(nil),        // 5: zeus.game.farm.v1.PlantFarmLandResponse
	(*FruitAcquireInfoList)(nil),         // 6: zeus.game.farm.v1.FruitAcquireInfoList
	(*FarmLandInfoList)(nil),             // 7: zeus.game.farm.v1.FarmLandInfoList
	(*Error)(nil),                        // 8: zeus.game.error.v1.Error
	(*FarmLandInfo)(nil),                 // 9: zeus.game.farm.v1.FarmLandInfo
}
var file_farm_proto_depIdxs = []int32{
	6, // 0: zeus.game.farm.v1.FruitAcquireInfoListResponse.list:type_name -> zeus.game.farm.v1.FruitAcquireInfoList
	7, // 1: zeus.game.farm.v1.FarmLandInfoListResponse.land_list:type_name -> zeus.game.farm.v1.FarmLandInfoList
	8, // 2: zeus.game.farm.v1.PlantFarmLandResponse.error:type_name -> zeus.game.error.v1.Error
	9, // 3: zeus.game.farm.v1.PlantFarmLandResponse.land_info:type_name -> zeus.game.farm.v1.FarmLandInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_farm_proto_init() }
func file_farm_proto_init() {
	if File_farm_proto != nil {
		return
	}
	file_err_code_proto_init()
	file_farm_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farm_proto_rawDesc), len(file_farm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_farm_proto_goTypes,
		DependencyIndexes: file_farm_proto_depIdxs,
		MessageInfos:      file_farm_proto_msgTypes,
	}.Build()
	File_farm_proto = out.File
	file_farm_proto_goTypes = nil
	file_farm_proto_depIdxs = nil
}
