// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: farm_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 每轮水果收购赔率 & 概率信息
type FruitAcquireInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemCfgId     uint32                 `protobuf:"varint,1,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` // 道具配置 id（水果种子 ItemConfig ID）
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`                         // 权重
	Probability   float32                `protobuf:"fixed32,3,opt,name=probability,proto3" json:"probability,omitempty"`               // 收购概率
	Odds          float32                `protobuf:"fixed32,4,opt,name=odds,proto3" json:"odds,omitempty"`                             // 收购赔率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FruitAcquireInfo) Reset() {
	*x = FruitAcquireInfo{}
	mi := &file_farm_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitAcquireInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitAcquireInfo) ProtoMessage() {}

func (x *FruitAcquireInfo) ProtoReflect() protoreflect.Message {
	mi := &file_farm_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitAcquireInfo.ProtoReflect.Descriptor instead.
func (*FruitAcquireInfo) Descriptor() ([]byte, []int) {
	return file_farm_type_proto_rawDescGZIP(), []int{0}
}

func (x *FruitAcquireInfo) GetItemCfgId() uint32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *FruitAcquireInfo) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *FruitAcquireInfo) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *FruitAcquireInfo) GetOdds() float32 {
	if x != nil {
		return x.Odds
	}
	return 0
}

// 每轮水果收购赔率 & 概率信息列表
type FruitAcquireInfoList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcquireInfoList []*FruitAcquireInfo    `protobuf:"bytes,1,rep,name=acquire_info_list,json=acquireInfoList,proto3" json:"acquire_info_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FruitAcquireInfoList) Reset() {
	*x = FruitAcquireInfoList{}
	mi := &file_farm_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FruitAcquireInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FruitAcquireInfoList) ProtoMessage() {}

func (x *FruitAcquireInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_farm_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FruitAcquireInfoList.ProtoReflect.Descriptor instead.
func (*FruitAcquireInfoList) Descriptor() ([]byte, []int) {
	return file_farm_type_proto_rawDescGZIP(), []int{1}
}

func (x *FruitAcquireInfoList) GetAcquireInfoList() []*FruitAcquireInfo {
	if x != nil {
		return x.AcquireInfoList
	}
	return nil
}

// 玩家一块田地信息
type FarmLandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandId        uint32                 `protobuf:"varint,1,opt,name=land_id,json=landId,proto3" json:"land_id,omitempty"`            // 第几块田（1~N）
	ItemCfgId     uint32                 `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` // 当前种植的道具配置 id（0 表示空地）
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // 种植数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmLandInfo) Reset() {
	*x = FarmLandInfo{}
	mi := &file_farm_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmLandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmLandInfo) ProtoMessage() {}

func (x *FarmLandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_farm_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmLandInfo.ProtoReflect.Descriptor instead.
func (*FarmLandInfo) Descriptor() ([]byte, []int) {
	return file_farm_type_proto_rawDescGZIP(), []int{2}
}

func (x *FarmLandInfo) GetLandId() uint32 {
	if x != nil {
		return x.LandId
	}
	return 0
}

func (x *FarmLandInfo) GetItemCfgId() uint32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *FarmLandInfo) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 玩家田地列表
type FarmLandInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LandList      []*FarmLandInfo        `protobuf:"bytes,1,rep,name=land_list,json=landList,proto3" json:"land_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmLandInfoList) Reset() {
	*x = FarmLandInfoList{}
	mi := &file_farm_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmLandInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmLandInfoList) ProtoMessage() {}

func (x *FarmLandInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_farm_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmLandInfoList.ProtoReflect.Descriptor instead.
func (*FarmLandInfoList) Descriptor() ([]byte, []int) {
	return file_farm_type_proto_rawDescGZIP(), []int{3}
}

func (x *FarmLandInfoList) GetLandList() []*FarmLandInfo {
	if x != nil {
		return x.LandList
	}
	return nil
}

var File_farm_type_proto protoreflect.FileDescriptor

const file_farm_type_proto_rawDesc = "" +
	"\n" +
	"\x0ffarm_type.proto\x12\x11zeus.game.farm.v1\"\x80\x01\n" +
	"\x10FruitAcquireInfo\x12\x1e\n" +
	"\vitem_cfg_id\x18\x01 \x01(\rR\titemCfgId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\x12 \n" +
	"\vprobability\x18\x03 \x01(\x02R\vprobability\x12\x12\n" +
	"\x04odds\x18\x04 \x01(\x02R\x04odds\"g\n" +
	"\x14FruitAcquireInfoList\x12O\n" +
	"\x11acquire_info_list\x18\x01 \x03(\v2#.zeus.game.farm.v1.FruitAcquireInfoR\x0facquireInfoList\"_\n" +
	"\fFarmLandInfo\x12\x17\n" +
	"\aland_id\x18\x01 \x01(\rR\x06landId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\rR\titemCfgId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\"P\n" +
	"\x10FarmLandInfoList\x12<\n" +
	"\tland_list\x18\x01 \x03(\v2\x1f.zeus.game.farm.v1.FarmLandInfoR\blandListB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_farm_type_proto_rawDescOnce sync.Once
	file_farm_type_proto_rawDescData []byte
)

func file_farm_type_proto_rawDescGZIP() []byte {
	file_farm_type_proto_rawDescOnce.Do(func() {
		file_farm_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_farm_type_proto_rawDesc), len(file_farm_type_proto_rawDesc)))
	})
	return file_farm_type_proto_rawDescData
}

var file_farm_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_farm_type_proto_goTypes = []any{
	(*FruitAcquireInfo)(nil),     // 0: zeus.game.farm.v1.FruitAcquireInfo
	(*FruitAcquireInfoList)(nil), // 1: zeus.game.farm.v1.FruitAcquireInfoList
	(*FarmLandInfo)(nil),         // 2: zeus.game.farm.v1.FarmLandInfo
	(*FarmLandInfoList)(nil),     // 3: zeus.game.farm.v1.FarmLandInfoList
}
var file_farm_type_proto_depIdxs = []int32{
	0, // 0: zeus.game.farm.v1.FruitAcquireInfoList.acquire_info_list:type_name -> zeus.game.farm.v1.FruitAcquireInfo
	2, // 1: zeus.game.farm.v1.FarmLandInfoList.land_list:type_name -> zeus.game.farm.v1.FarmLandInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_farm_type_proto_init() }
func file_farm_type_proto_init() {
	if File_farm_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_farm_type_proto_rawDesc), len(file_farm_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_farm_type_proto_goTypes,
		DependencyIndexes: file_farm_type_proto_depIdxs,
		MessageInfos:      file_farm_type_proto_msgTypes,
	}.Build()
	File_farm_type_proto = out.File
	file_farm_type_proto_goTypes = nil
	file_farm_type_proto_depIdxs = nil
}
