// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: fashion.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 手动换装 - 请求
type DressChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 要穿戴的道具实例 ID（ItemInfo.item_id）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DressChangeRequest) Reset() {
	*x = DressChangeRequest{}
	mi := &file_fashion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DressChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DressChangeRequest) ProtoMessage() {}

func (x *DressChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fashion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DressChangeRequest.ProtoReflect.Descriptor instead.
func (*DressChangeRequest) Descriptor() ([]byte, []int) {
	return file_fashion_proto_rawDescGZIP(), []int{0}
}

func (x *DressChangeRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

// 手动换装 - 回复
type DressChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Item          *ItemInfo              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"` // 当前穿戴的服饰详细信息（成功时返回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DressChangeResponse) Reset() {
	*x = DressChangeResponse{}
	mi := &file_fashion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DressChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DressChangeResponse) ProtoMessage() {}

func (x *DressChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fashion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DressChangeResponse.ProtoReflect.Descriptor instead.
func (*DressChangeResponse) Descriptor() ([]byte, []int) {
	return file_fashion_proto_rawDescGZIP(), []int{1}
}

func (x *DressChangeResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DressChangeResponse) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

// 手动换装 - 通知所有人（主画面更新）
type DressChangeNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 改装的角色 ID
	Item          *ItemInfo              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DressChangeNotify) Reset() {
	*x = DressChangeNotify{}
	mi := &file_fashion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DressChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DressChangeNotify) ProtoMessage() {}

func (x *DressChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_fashion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DressChangeNotify.ProtoReflect.Descriptor instead.
func (*DressChangeNotify) Descriptor() ([]byte, []int) {
	return file_fashion_proto_rawDescGZIP(), []int{2}
}

func (x *DressChangeNotify) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DressChangeNotify) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_fashion_proto protoreflect.FileDescriptor

const file_fashion_proto_rawDesc = "" +
	"\n" +
	"\rfashion.proto\x12\x14zeus.game.fashion.v1\x1a\x0fitem_type.proto\x1a\x0eerr_code.proto\"-\n" +
	"\x12DressChangeRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x04R\x06itemId\"w\n" +
	"\x13DressChangeResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12/\n" +
	"\x04item\x18\x02 \x01(\v2\x1b.zeus.game.item.v1.ItemInfoR\x04item\"]\n" +
	"\x11DressChangeNotify\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12/\n" +
	"\x04item\x18\x02 \x01(\v2\x1b.zeus.game.item.v1.ItemInfoR\x04itemB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_fashion_proto_rawDescOnce sync.Once
	file_fashion_proto_rawDescData []byte
)

func file_fashion_proto_rawDescGZIP() []byte {
	file_fashion_proto_rawDescOnce.Do(func() {
		file_fashion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fashion_proto_rawDesc), len(file_fashion_proto_rawDesc)))
	})
	return file_fashion_proto_rawDescData
}

var file_fashion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fashion_proto_goTypes = []any{
	(*DressChangeRequest)(nil),  // 0: zeus.game.fashion.v1.DressChangeRequest
	(*DressChangeResponse)(nil), // 1: zeus.game.fashion.v1.DressChangeResponse
	(*DressChangeNotify)(nil),   // 2: zeus.game.fashion.v1.DressChangeNotify
	(*Error)(nil),               // 3: zeus.game.error.v1.Error
	(*ItemInfo)(nil),            // 4: zeus.game.item.v1.ItemInfo
}
var file_fashion_proto_depIdxs = []int32{
	3, // 0: zeus.game.fashion.v1.DressChangeResponse.error:type_name -> zeus.game.error.v1.Error
	4, // 1: zeus.game.fashion.v1.DressChangeResponse.item:type_name -> zeus.game.item.v1.ItemInfo
	4, // 2: zeus.game.fashion.v1.DressChangeNotify.item:type_name -> zeus.game.item.v1.ItemInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_fashion_proto_init() }
func file_fashion_proto_init() {
	if File_fashion_proto != nil {
		return
	}
	file_item_type_proto_init()
	file_err_code_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fashion_proto_rawDesc), len(file_fashion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fashion_proto_goTypes,
		DependencyIndexes: file_fashion_proto_depIdxs,
		MessageInfos:      file_fashion_proto_msgTypes,
	}.Build()
	File_fashion_proto = out.File
	file_fashion_proto_goTypes = nil
	file_fashion_proto_depIdxs = nil
}
