// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: item.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemExpiredNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpiredItemIds []uint64               `protobuf:"varint,1,rep,packed,name=expired_item_ids,json=expiredItemIds,proto3" json:"expired_item_ids,omitempty"` // 被删除的 item_id 列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ItemExpiredNotify) Reset() {
	*x = ItemExpiredNotify{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemExpiredNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemExpiredNotify) ProtoMessage() {}

func (x *ItemExpiredNotify) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemExpiredNotify.ProtoReflect.Descriptor instead.
func (*ItemExpiredNotify) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemExpiredNotify) GetExpiredItemIds() []uint64 {
	if x != nil {
		return x.ExpiredItemIds
	}
	return nil
}

// 获取道具列表 - 请求
type ItemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListRequest) Reset() {
	*x = ItemListRequest{}
	mi := &file_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListRequest) ProtoMessage() {}

func (x *ItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListRequest.ProtoReflect.Descriptor instead.
func (*ItemListRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

// 获取道具列表 - 回应
type ItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfo            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 全部可用服饰
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListResponse) Reset() {
	*x = ItemListResponse{}
	mi := &file_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListResponse) ProtoMessage() {}

func (x *ItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListResponse.ProtoReflect.Descriptor instead.
func (*ItemListResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemListResponse) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\x11zeus.game.item.v1\x1a\x0fitem_type.proto\"=\n" +
	"\x11ItemExpiredNotify\x12(\n" +
	"\x10expired_item_ids\x18\x01 \x03(\x04R\x0eexpiredItemIds\"\x11\n" +
	"\x0fItemListRequest\"E\n" +
	"\x10ItemListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.zeus.game.item.v1.ItemInfoR\x05itemsB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_item_proto_goTypes = []any{
	(*ItemExpiredNotify)(nil), // 0: zeus.game.item.v1.ItemExpiredNotify
	(*ItemListRequest)(nil),   // 1: zeus.game.item.v1.ItemListRequest
	(*ItemListResponse)(nil),  // 2: zeus.game.item.v1.ItemListResponse
	(*ItemInfo)(nil),          // 3: zeus.game.item.v1.ItemInfo
}
var file_item_proto_depIdxs = []int32{
	3, // 0: zeus.game.item.v1.ItemListResponse.items:type_name -> zeus.game.item.v1.ItemInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	file_item_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
