// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: item_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemCategory int32

const (
	ItemCategory_ITEM_CATEGORY_UNKNOWN ItemCategory = 0
	// 服装 / 外观大类
	ItemCategory_ITEM_CATEGORY_FASHION ItemCategory = 1
	// 种田系统道具（种子、肥料、催熟等）
	ItemCategory_ITEM_CATEGORY_FARM ItemCategory = 2
	// 床位系统道具（护盾、封印、踢人等）
	ItemCategory_ITEM_CATEGORY_BED ItemCategory = 3
	// 消耗品（通用）
	ItemCategory_ITEM_CATEGORY_CONSUMABLE ItemCategory = 4
	// 特殊道具（礼包、经验卡等）
	ItemCategory_ITEM_CATEGORY_SPECIAL ItemCategory = 5
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ITEM_CATEGORY_UNKNOWN",
		1: "ITEM_CATEGORY_FASHION",
		2: "ITEM_CATEGORY_FARM",
		3: "ITEM_CATEGORY_BED",
		4: "ITEM_CATEGORY_CONSUMABLE",
		5: "ITEM_CATEGORY_SPECIAL",
	}
	ItemCategory_value = map[string]int32{
		"ITEM_CATEGORY_UNKNOWN":    0,
		"ITEM_CATEGORY_FASHION":    1,
		"ITEM_CATEGORY_FARM":       2,
		"ITEM_CATEGORY_BED":        3,
		"ITEM_CATEGORY_CONSUMABLE": 4,
		"ITEM_CATEGORY_SPECIAL":    5,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_item_type_proto_enumTypes[0].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_item_type_proto_enumTypes[0]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{0}
}

type ItemSubType int32

const (
	ItemSubType_ITEM_SUBTYPE_UNKNOWN ItemSubType = 0
	// -------- 服装类（外观大类） --------
	ItemSubType_ITEM_SUBTYPE_CLOTH     ItemSubType = 1 // 衣服
	ItemSubType_ITEM_SUBTYPE_HAT       ItemSubType = 2 // 帽子
	ItemSubType_ITEM_SUBTYPE_SHOES     ItemSubType = 3 // 鞋子
	ItemSubType_ITEM_SUBTYPE_PANTS     ItemSubType = 4 // 裤子
	ItemSubType_ITEM_SUBTYPE_FACE      ItemSubType = 5 // 脸部（如口罩、表情）
	ItemSubType_ITEM_SUBTYPE_ACCESSORY ItemSubType = 6 // 饰品（项链、耳环等）
	// -------- 种田分类 --------
	ItemSubType_ITEM_SUBTYPE_FARM_FRUIT_SEED ItemSubType = 20 // 水果种子
	// -------- 通用消耗品 --------
	ItemSubType_ITEM_SUBTYPE_CONSUMABLE ItemSubType = 60
)

// Enum value maps for ItemSubType.
var (
	ItemSubType_name = map[int32]string{
		0:  "ITEM_SUBTYPE_UNKNOWN",
		1:  "ITEM_SUBTYPE_CLOTH",
		2:  "ITEM_SUBTYPE_HAT",
		3:  "ITEM_SUBTYPE_SHOES",
		4:  "ITEM_SUBTYPE_PANTS",
		5:  "ITEM_SUBTYPE_FACE",
		6:  "ITEM_SUBTYPE_ACCESSORY",
		20: "ITEM_SUBTYPE_FARM_FRUIT_SEED",
		60: "ITEM_SUBTYPE_CONSUMABLE",
	}
	ItemSubType_value = map[string]int32{
		"ITEM_SUBTYPE_UNKNOWN":         0,
		"ITEM_SUBTYPE_CLOTH":           1,
		"ITEM_SUBTYPE_HAT":             2,
		"ITEM_SUBTYPE_SHOES":           3,
		"ITEM_SUBTYPE_PANTS":           4,
		"ITEM_SUBTYPE_FACE":            5,
		"ITEM_SUBTYPE_ACCESSORY":       6,
		"ITEM_SUBTYPE_FARM_FRUIT_SEED": 20,
		"ITEM_SUBTYPE_CONSUMABLE":      60,
	}
)

func (x ItemSubType) Enum() *ItemSubType {
	p := new(ItemSubType)
	*p = x
	return p
}

func (x ItemSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_item_type_proto_enumTypes[1].Descriptor()
}

func (ItemSubType) Type() protoreflect.EnumType {
	return &file_item_type_proto_enumTypes[1]
}

func (x ItemSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemSubType.Descriptor instead.
func (ItemSubType) EnumDescriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{1}
}

// 道具品质
type ItemQuality int32

const (
	ItemQuality_ITEM_QUALITY_UNKNOWN ItemQuality = 0
	ItemQuality_ITEM_QUALITY_SSR     ItemQuality = 1
	ItemQuality_ITEM_QUALITY_SR      ItemQuality = 2
	ItemQuality_ITEM_QUALITY_R       ItemQuality = 3
	ItemQuality_ITEM_QUALITY_N       ItemQuality = 4
)

// Enum value maps for ItemQuality.
var (
	ItemQuality_name = map[int32]string{
		0: "ITEM_QUALITY_UNKNOWN",
		1: "ITEM_QUALITY_SSR",
		2: "ITEM_QUALITY_SR",
		3: "ITEM_QUALITY_R",
		4: "ITEM_QUALITY_N",
	}
	ItemQuality_value = map[string]int32{
		"ITEM_QUALITY_UNKNOWN": 0,
		"ITEM_QUALITY_SSR":     1,
		"ITEM_QUALITY_SR":      2,
		"ITEM_QUALITY_R":       3,
		"ITEM_QUALITY_N":       4,
	}
)

func (x ItemQuality) Enum() *ItemQuality {
	p := new(ItemQuality)
	*p = x
	return p
}

func (x ItemQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_item_type_proto_enumTypes[2].Descriptor()
}

func (ItemQuality) Type() protoreflect.EnumType {
	return &file_item_type_proto_enumTypes[2]
}

func (x ItemQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemQuality.Descriptor instead.
func (ItemQuality) EnumDescriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{2}
}

// 道具类型
type ItemType int32

const (
	ItemType_ITEM_TYPE_UNKNOWN ItemType = 0
	ItemType_ITEM_TYPE_CLOTH   ItemType = 1 // 衣服
	ItemType_ITEM_TYPE_AVATAR  ItemType = 2 // 头像
	ItemType_ITEM_TYPE_BUBBLE  ItemType = 3 // 气泡框
	ItemType_ITEM_TYPE_OTHER   ItemType = 9 // 后续拓展
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNKNOWN",
		1: "ITEM_TYPE_CLOTH",
		2: "ITEM_TYPE_AVATAR",
		3: "ITEM_TYPE_BUBBLE",
		9: "ITEM_TYPE_OTHER",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNKNOWN": 0,
		"ITEM_TYPE_CLOTH":   1,
		"ITEM_TYPE_AVATAR":  2,
		"ITEM_TYPE_BUBBLE":  3,
		"ITEM_TYPE_OTHER":   9,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_item_type_proto_enumTypes[3].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_item_type_proto_enumTypes[3]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{3}
}

// 通用 Item 道具结构
type ItemInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ConfigId uint64                 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                                 // 配表 ID（唯一静态 ID）
	Category ItemCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=zeus.game.item.v1.ItemCategory" json:"category,omitempty"`             // 大类，例如 FASHION
	SubType  ItemSubType            `protobuf:"varint,3,opt,name=sub_type,json=subType,proto3,enum=zeus.game.item.v1.ItemSubType" json:"sub_type,omitempty"` // 小类，例如 HAT
	Quality  ItemQuality            `protobuf:"varint,4,opt,name=quality,proto3,enum=zeus.game.item.v1.ItemQuality" json:"quality,omitempty"`                // 品质（SSR/SR/R/N）
	// 是否为消耗品（购买后直接使用，不进背包）
	Consumable bool `protobuf:"varint,5,opt,name=consumable,proto3" json:"consumable,omitempty"`
	// 售卖价格
	Prices []*ItemPrice `protobuf:"bytes,6,rep,name=prices,proto3" json:"prices,omitempty"`
	// 使用期限（秒级时间戳），0 = 永久
	ExpireAt int64 `protobuf:"varint,7,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// 展示相关
	Name          string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_item_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_item_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInfo) GetConfigId() uint64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ItemInfo) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNKNOWN
}

func (x *ItemInfo) GetSubType() ItemSubType {
	if x != nil {
		return x.SubType
	}
	return ItemSubType_ITEM_SUBTYPE_UNKNOWN
}

func (x *ItemInfo) GetQuality() ItemQuality {
	if x != nil {
		return x.Quality
	}
	return ItemQuality_ITEM_QUALITY_UNKNOWN
}

func (x *ItemInfo) GetConsumable() bool {
	if x != nil {
		return x.Consumable
	}
	return false
}

func (x *ItemInfo) GetPrices() []*ItemPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *ItemInfo) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *ItemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ItemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 道具价格（消耗的资源类型与数量）
type ItemPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ResourceType           `protobuf:"varint,1,opt,name=type,proto3,enum=zeus.game.resource.v1.ResourceType" json:"type,omitempty"` // 资源类型
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                                     // 消耗数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemPrice) Reset() {
	*x = ItemPrice{}
	mi := &file_item_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPrice) ProtoMessage() {}

func (x *ItemPrice) ProtoReflect() protoreflect.Message {
	mi := &file_item_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPrice.ProtoReflect.Descriptor instead.
func (*ItemPrice) Descriptor() ([]byte, []int) {
	return file_item_type_proto_rawDescGZIP(), []int{1}
}

func (x *ItemPrice) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_UNKNOWN
}

func (x *ItemPrice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_item_type_proto protoreflect.FileDescriptor

const file_item_type_proto_rawDesc = "" +
	"\n" +
	"\x0fitem_type.proto\x12\x11zeus.game.item.v1\x1a\x0eresource.proto\"\x96\x03\n" +
	"\bItemInfo\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\x04R\bconfigId\x12;\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1f.zeus.game.item.v1.ItemCategoryR\bcategory\x129\n" +
	"\bsub_type\x18\x03 \x01(\x0e2\x1e.zeus.game.item.v1.ItemSubTypeR\asubType\x128\n" +
	"\aquality\x18\x04 \x01(\x0e2\x1e.zeus.game.item.v1.ItemQualityR\aquality\x12\x1e\n" +
	"\n" +
	"consumable\x18\x05 \x01(\bR\n" +
	"consumable\x124\n" +
	"\x06prices\x18\x06 \x03(\v2\x1c.zeus.game.item.v1.ItemPriceR\x06prices\x12\x1b\n" +
	"\texpire_at\x18\a \x01(\x03R\bexpireAt\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\\\n" +
	"\tItemPrice\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.zeus.game.resource.v1.ResourceTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount*\xac\x01\n" +
	"\fItemCategory\x12\x19\n" +
	"\x15ITEM_CATEGORY_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ITEM_CATEGORY_FASHION\x10\x01\x12\x16\n" +
	"\x12ITEM_CATEGORY_FARM\x10\x02\x12\x15\n" +
	"\x11ITEM_CATEGORY_BED\x10\x03\x12\x1c\n" +
	"\x18ITEM_CATEGORY_CONSUMABLE\x10\x04\x12\x19\n" +
	"\x15ITEM_CATEGORY_SPECIAL\x10\x05*\xf7\x01\n" +
	"\vItemSubType\x12\x18\n" +
	"\x14ITEM_SUBTYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ITEM_SUBTYPE_CLOTH\x10\x01\x12\x14\n" +
	"\x10ITEM_SUBTYPE_HAT\x10\x02\x12\x16\n" +
	"\x12ITEM_SUBTYPE_SHOES\x10\x03\x12\x16\n" +
	"\x12ITEM_SUBTYPE_PANTS\x10\x04\x12\x15\n" +
	"\x11ITEM_SUBTYPE_FACE\x10\x05\x12\x1a\n" +
	"\x16ITEM_SUBTYPE_ACCESSORY\x10\x06\x12 \n" +
	"\x1cITEM_SUBTYPE_FARM_FRUIT_SEED\x10\x14\x12\x1b\n" +
	"\x17ITEM_SUBTYPE_CONSUMABLE\x10<*z\n" +
	"\vItemQuality\x12\x18\n" +
	"\x14ITEM_QUALITY_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ITEM_QUALITY_SSR\x10\x01\x12\x13\n" +
	"\x0fITEM_QUALITY_SR\x10\x02\x12\x12\n" +
	"\x0eITEM_QUALITY_R\x10\x03\x12\x12\n" +
	"\x0eITEM_QUALITY_N\x10\x04*w\n" +
	"\bItemType\x12\x15\n" +
	"\x11ITEM_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fITEM_TYPE_CLOTH\x10\x01\x12\x14\n" +
	"\x10ITEM_TYPE_AVATAR\x10\x02\x12\x14\n" +
	"\x10ITEM_TYPE_BUBBLE\x10\x03\x12\x13\n" +
	"\x0fITEM_TYPE_OTHER\x10\tB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_item_type_proto_rawDescOnce sync.Once
	file_item_type_proto_rawDescData []byte
)

func file_item_type_proto_rawDescGZIP() []byte {
	file_item_type_proto_rawDescOnce.Do(func() {
		file_item_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_type_proto_rawDesc), len(file_item_type_proto_rawDesc)))
	})
	return file_item_type_proto_rawDescData
}

var file_item_type_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_item_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_type_proto_goTypes = []any{
	(ItemCategory)(0), // 0: zeus.game.item.v1.ItemCategory
	(ItemSubType)(0),  // 1: zeus.game.item.v1.ItemSubType
	(ItemQuality)(0),  // 2: zeus.game.item.v1.ItemQuality
	(ItemType)(0),     // 3: zeus.game.item.v1.ItemType
	(*ItemInfo)(nil),  // 4: zeus.game.item.v1.ItemInfo
	(*ItemPrice)(nil), // 5: zeus.game.item.v1.ItemPrice
	(ResourceType)(0), // 6: zeus.game.resource.v1.ResourceType
}
var file_item_type_proto_depIdxs = []int32{
	0, // 0: zeus.game.item.v1.ItemInfo.category:type_name -> zeus.game.item.v1.ItemCategory
	1, // 1: zeus.game.item.v1.ItemInfo.sub_type:type_name -> zeus.game.item.v1.ItemSubType
	2, // 2: zeus.game.item.v1.ItemInfo.quality:type_name -> zeus.game.item.v1.ItemQuality
	5, // 3: zeus.game.item.v1.ItemInfo.prices:type_name -> zeus.game.item.v1.ItemPrice
	6, // 4: zeus.game.item.v1.ItemPrice.type:type_name -> zeus.game.resource.v1.ResourceType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_item_type_proto_init() }
func file_item_type_proto_init() {
	if File_item_type_proto != nil {
		return
	}
	file_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_type_proto_rawDesc), len(file_item_type_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_type_proto_goTypes,
		DependencyIndexes: file_item_type_proto_depIdxs,
		EnumInfos:         file_item_type_proto_enumTypes,
		MessageInfos:      file_item_type_proto_msgTypes,
	}.Build()
	File_item_type_proto = out.File
	file_item_type_proto_goTypes = nil
	file_item_type_proto_depIdxs = nil
}
