// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: role.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 切换角色（如切换男女） - 请求
type SwitchRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       uint64                 `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 要切换到的角色 ID（如男女两个角色）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRoleRequest) Reset() {
	*x = SwitchRoleRequest{}
	mi := &file_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRoleRequest) ProtoMessage() {}

func (x *SwitchRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRoleRequest.ProtoReflect.Descriptor instead.
func (*SwitchRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchRoleRequest) GetModelId() uint64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

// 切换角色 - 响应
type SwitchRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Role          *BaseRoleInfo          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // 切换后的角色完整信息（含 appearance）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRoleResponse) Reset() {
	*x = SwitchRoleResponse{}
	mi := &file_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRoleResponse) ProtoMessage() {}

func (x *SwitchRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRoleResponse.ProtoReflect.Descriptor instead.
func (*SwitchRoleResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchRoleResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SwitchRoleResponse) GetRole() *BaseRoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

// 切换角色 - 通知其他玩家
type SwitchRoleNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint64                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 操作的玩家 ID
	Role          *BaseRoleInfo          `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                          // 切换后的角色数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchRoleNotify) Reset() {
	*x = SwitchRoleNotify{}
	mi := &file_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchRoleNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchRoleNotify) ProtoMessage() {}

func (x *SwitchRoleNotify) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchRoleNotify.ProtoReflect.Descriptor instead.
func (*SwitchRoleNotify) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *SwitchRoleNotify) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SwitchRoleNotify) GetRole() *BaseRoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

// 获取角色列表（用于角色选择界面）
type RoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListRequest) Reset() {
	*x = RoleListRequest{}
	mi := &file_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListRequest) ProtoMessage() {}

func (x *RoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListRequest.ProtoReflect.Descriptor instead.
func (*RoleListRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

// 获取角色列表 - 响应
type RoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*BaseRoleInfo        `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"` // 用户拥有的所有角色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResponse) Reset() {
	*x = RoleListResponse{}
	mi := &file_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResponse) ProtoMessage() {}

func (x *RoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResponse.ProtoReflect.Descriptor instead.
func (*RoleListResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

func (x *RoleListResponse) GetRoles() []*BaseRoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_role_proto protoreflect.FileDescriptor

const file_role_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"role.proto\x12\x11zeus.game.role.v1\x1a\x0eerr_code.proto\x1a\x0frole_type.proto\".\n" +
	"\x11SwitchRoleRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x04R\amodelId\"z\n" +
	"\x12SwitchRoleResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x123\n" +
	"\x04role\x18\x02 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x04role\"d\n" +
	"\x10SwitchRoleNotify\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x04R\btargetId\x123\n" +
	"\x04role\x18\x02 \x01(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x04role\"\x11\n" +
	"\x0fRoleListRequest\"I\n" +
	"\x10RoleListResponse\x125\n" +
	"\x05roles\x18\x01 \x03(\v2\x1f.zeus.game.role.v1.BaseRoleInfoR\x05rolesB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData []byte
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)))
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_role_proto_goTypes = []any{
	(*SwitchRoleRequest)(nil),  // 0: zeus.game.role.v1.SwitchRoleRequest
	(*SwitchRoleResponse)(nil), // 1: zeus.game.role.v1.SwitchRoleResponse
	(*SwitchRoleNotify)(nil),   // 2: zeus.game.role.v1.SwitchRoleNotify
	(*RoleListRequest)(nil),    // 3: zeus.game.role.v1.RoleListRequest
	(*RoleListResponse)(nil),   // 4: zeus.game.role.v1.RoleListResponse
	(*Error)(nil),              // 5: zeus.game.error.v1.Error
	(*BaseRoleInfo)(nil),       // 6: zeus.game.role.v1.BaseRoleInfo
}
var file_role_proto_depIdxs = []int32{
	5, // 0: zeus.game.role.v1.SwitchRoleResponse.error:type_name -> zeus.game.error.v1.Error
	6, // 1: zeus.game.role.v1.SwitchRoleResponse.role:type_name -> zeus.game.role.v1.BaseRoleInfo
	6, // 2: zeus.game.role.v1.SwitchRoleNotify.role:type_name -> zeus.game.role.v1.BaseRoleInfo
	6, // 3: zeus.game.role.v1.RoleListResponse.roles:type_name -> zeus.game.role.v1.BaseRoleInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_err_code_proto_init()
	file_role_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
