// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: role_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色外观信息（可扩展结构）
type CharacterAppearance struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId uint64                 `protobuf:"varint,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // 角色基础模型（男女模型等）
	// 捏脸细节字段（可根据美术需求扩展）
	HairId        uint64 `protobuf:"varint,2,opt,name=hair_id,json=hairId,proto3" json:"hair_id,omitempty"`                  // 发型
	EyebrowId     uint64 `protobuf:"varint,3,opt,name=eyebrow_id,json=eyebrowId,proto3" json:"eyebrow_id,omitempty"`         // 眉毛
	EyeId         uint64 `protobuf:"varint,4,opt,name=eye_id,json=eyeId,proto3" json:"eye_id,omitempty"`                     // 眼睛
	NoseId        uint64 `protobuf:"varint,5,opt,name=nose_id,json=noseId,proto3" json:"nose_id,omitempty"`                  // 鼻子
	MouthId       uint64 `protobuf:"varint,6,opt,name=mouth_id,json=mouthId,proto3" json:"mouth_id,omitempty"`               // 嘴
	FaceShapeId   uint64 `protobuf:"varint,7,opt,name=face_shape_id,json=faceShapeId,proto3" json:"face_shape_id,omitempty"` // 脸型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterAppearance) Reset() {
	*x = CharacterAppearance{}
	mi := &file_role_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAppearance) ProtoMessage() {}

func (x *CharacterAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_role_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAppearance.ProtoReflect.Descriptor instead.
func (*CharacterAppearance) Descriptor() ([]byte, []int) {
	return file_role_type_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterAppearance) GetModelId() uint64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *CharacterAppearance) GetHairId() uint64 {
	if x != nil {
		return x.HairId
	}
	return 0
}

func (x *CharacterAppearance) GetEyebrowId() uint64 {
	if x != nil {
		return x.EyebrowId
	}
	return 0
}

func (x *CharacterAppearance) GetEyeId() uint64 {
	if x != nil {
		return x.EyeId
	}
	return 0
}

func (x *CharacterAppearance) GetNoseId() uint64 {
	if x != nil {
		return x.NoseId
	}
	return 0
}

func (x *CharacterAppearance) GetMouthId() uint64 {
	if x != nil {
		return x.MouthId
	}
	return 0
}

func (x *CharacterAppearance) GetFaceShapeId() uint64 {
	if x != nil {
		return x.FaceShapeId
	}
	return 0
}

// 角色基础展示信息
type BaseRoleInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvatarId       uint64                 `protobuf:"varint,1,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`                     // 角色头像 ID
	RoleId         uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                           // 角色 ID
	ClothId        uint64                 `protobuf:"varint,3,opt,name=cloth_id,json=clothId,proto3" json:"cloth_id,omitempty"`                        // 衣服 ID
	BubbleId       uint64                 `protobuf:"varint,4,opt,name=bubble_id,json=bubbleId,proto3" json:"bubble_id,omitempty"`                     // 气泡 ID
	BubbleText     string                 `protobuf:"bytes,5,opt,name=bubble_text,json=bubbleText,proto3" json:"bubble_text,omitempty"`                // 气泡文本
	RoleName       string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`                      // 角色名称
	RelationCardId uint64                 `protobuf:"varint,7,opt,name=relation_card_id,json=relationCardId,proto3" json:"relation_card_id,omitempty"` // 关系牌 ID
	Appearance     *CharacterAppearance   `protobuf:"bytes,8,opt,name=appearance,proto3" json:"appearance,omitempty"`                                  // 角色外观（模型与捏脸数据）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseRoleInfo) Reset() {
	*x = BaseRoleInfo{}
	mi := &file_role_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRoleInfo) ProtoMessage() {}

func (x *BaseRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRoleInfo.ProtoReflect.Descriptor instead.
func (*BaseRoleInfo) Descriptor() ([]byte, []int) {
	return file_role_type_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRoleInfo) GetAvatarId() uint64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *BaseRoleInfo) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BaseRoleInfo) GetClothId() uint64 {
	if x != nil {
		return x.ClothId
	}
	return 0
}

func (x *BaseRoleInfo) GetBubbleId() uint64 {
	if x != nil {
		return x.BubbleId
	}
	return 0
}

func (x *BaseRoleInfo) GetBubbleText() string {
	if x != nil {
		return x.BubbleText
	}
	return ""
}

func (x *BaseRoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *BaseRoleInfo) GetRelationCardId() uint64 {
	if x != nil {
		return x.RelationCardId
	}
	return 0
}

func (x *BaseRoleInfo) GetAppearance() *CharacterAppearance {
	if x != nil {
		return x.Appearance
	}
	return nil
}

var File_role_type_proto protoreflect.FileDescriptor

const file_role_type_proto_rawDesc = "" +
	"\n" +
	"\x0frole_type.proto\x12\x11zeus.game.role.v1\"\xd7\x01\n" +
	"\x13CharacterAppearance\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\x04R\amodelId\x12\x17\n" +
	"\ahair_id\x18\x02 \x01(\x04R\x06hairId\x12\x1d\n" +
	"\n" +
	"eyebrow_id\x18\x03 \x01(\x04R\teyebrowId\x12\x15\n" +
	"\x06eye_id\x18\x04 \x01(\x04R\x05eyeId\x12\x17\n" +
	"\anose_id\x18\x05 \x01(\x04R\x06noseId\x12\x19\n" +
	"\bmouth_id\x18\x06 \x01(\x04R\amouthId\x12\"\n" +
	"\rface_shape_id\x18\a \x01(\x04R\vfaceShapeId\"\xac\x02\n" +
	"\fBaseRoleInfo\x12\x1b\n" +
	"\tavatar_id\x18\x01 \x01(\x04R\bavatarId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId\x12\x19\n" +
	"\bcloth_id\x18\x03 \x01(\x04R\aclothId\x12\x1b\n" +
	"\tbubble_id\x18\x04 \x01(\x04R\bbubbleId\x12\x1f\n" +
	"\vbubble_text\x18\x05 \x01(\tR\n" +
	"bubbleText\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\x12(\n" +
	"\x10relation_card_id\x18\a \x01(\x04R\x0erelationCardId\x12F\n" +
	"\n" +
	"appearance\x18\b \x01(\v2&.zeus.game.role.v1.CharacterAppearanceR\n" +
	"appearanceB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_role_type_proto_rawDescOnce sync.Once
	file_role_type_proto_rawDescData []byte
)

func file_role_type_proto_rawDescGZIP() []byte {
	file_role_type_proto_rawDescOnce.Do(func() {
		file_role_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_type_proto_rawDesc), len(file_role_type_proto_rawDesc)))
	})
	return file_role_type_proto_rawDescData
}

var file_role_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_role_type_proto_goTypes = []any{
	(*CharacterAppearance)(nil), // 0: zeus.game.role.v1.CharacterAppearance
	(*BaseRoleInfo)(nil),        // 1: zeus.game.role.v1.BaseRoleInfo
}
var file_role_type_proto_depIdxs = []int32{
	0, // 0: zeus.game.role.v1.BaseRoleInfo.appearance:type_name -> zeus.game.role.v1.CharacterAppearance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_role_type_proto_init() }
func file_role_type_proto_init() {
	if File_role_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_type_proto_rawDesc), len(file_role_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_type_proto_goTypes,
		DependencyIndexes: file_role_type_proto_depIdxs,
		MessageInfos:      file_role_type_proto_msgTypes,
	}.Build()
	File_role_type_proto = out.File
	file_role_type_proto_goTypes = nil
	file_role_type_proto_depIdxs = nil
}
