// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: shop_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商店类型
type ShopType int32

const (
	ShopType_SHOP_TYPE_UNKNOWN ShopType = 0 // 未指定
	// 全局兑换商店：面向所有玩家，共享配置与库存
	ShopType_SHOP_TYPE_GLOBAL_EXCHANGE ShopType = 1
	// 个人兑换商店：每个玩家独立的兑换商店（个人库存 / 进度）
	ShopType_SHOP_TYPE_PERSONAL_EXCHANGE ShopType = 2
)

// Enum value maps for ShopType.
var (
	ShopType_name = map[int32]string{
		0: "SHOP_TYPE_UNKNOWN",
		1: "SHOP_TYPE_GLOBAL_EXCHANGE",
		2: "SHOP_TYPE_PERSONAL_EXCHANGE",
	}
	ShopType_value = map[string]int32{
		"SHOP_TYPE_UNKNOWN":           0,
		"SHOP_TYPE_GLOBAL_EXCHANGE":   1,
		"SHOP_TYPE_PERSONAL_EXCHANGE": 2,
	}
)

func (x ShopType) Enum() *ShopType {
	p := new(ShopType)
	*p = x
	return p
}

func (x ShopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopType) Descriptor() protoreflect.EnumDescriptor {
	return file_shop_type_proto_enumTypes[0].Descriptor()
}

func (ShopType) Type() protoreflect.EnumType {
	return &file_shop_type_proto_enumTypes[0]
}

func (x ShopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopType.Descriptor instead.
func (ShopType) EnumDescriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{0}
}

// 商城商品结构
type ShopItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *ItemInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // 道具基本信息（含大类/子类/价格等）
	// 最大可兑换数量（0 表示无兑换限制）
	MaxExchangeNum uint64 `protobuf:"varint,2,opt,name=max_exchange_num,json=maxExchangeNum,proto3" json:"max_exchange_num,omitempty"`
	// 兑换价格（可覆盖 ItemInfo.prices 的默认配置）
	Prices        []*ItemPrice `protobuf:"bytes,3,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_shop_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_shop_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{0}
}

func (x *ShopItem) GetInfo() *ItemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ShopItem) GetMaxExchangeNum() uint64 {
	if x != nil {
		return x.MaxExchangeNum
	}
	return 0
}

func (x *ShopItem) GetPrices() []*ItemPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

// 商城道具列表
type ShopItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopType      ShopType               `protobuf:"varint,1,opt,name=shop_type,json=shopType,proto3,enum=zeus.game.shop.v1.ShopType" json:"shop_type,omitempty"` // 商店类型
	Items         []*ShopItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                                                        // 当前商店内的全部商品配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItemList) Reset() {
	*x = ShopItemList{}
	mi := &file_shop_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItemList) ProtoMessage() {}

func (x *ShopItemList) ProtoReflect() protoreflect.Message {
	mi := &file_shop_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItemList.ProtoReflect.Descriptor instead.
func (*ShopItemList) Descriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{1}
}

func (x *ShopItemList) GetShopType() ShopType {
	if x != nil {
		return x.ShopType
	}
	return ShopType_SHOP_TYPE_UNKNOWN
}

func (x *ShopItemList) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_shop_type_proto protoreflect.FileDescriptor

const file_shop_type_proto_rawDesc = "" +
	"\n" +
	"\x0fshop_type.proto\x12\x11zeus.game.shop.v1\x1a\x0fitem_type.proto\"\x9b\x01\n" +
	"\bShopItem\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.zeus.game.item.v1.ItemInfoR\x04info\x12(\n" +
	"\x10max_exchange_num\x18\x02 \x01(\x04R\x0emaxExchangeNum\x124\n" +
	"\x06prices\x18\x03 \x03(\v2\x1c.zeus.game.item.v1.ItemPriceR\x06prices\"{\n" +
	"\fShopItemList\x128\n" +
	"\tshop_type\x18\x01 \x01(\x0e2\x1b.zeus.game.shop.v1.ShopTypeR\bshopType\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.zeus.game.shop.v1.ShopItemR\x05items*a\n" +
	"\bShopType\x12\x15\n" +
	"\x11SHOP_TYPE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19SHOP_TYPE_GLOBAL_EXCHANGE\x10\x01\x12\x1f\n" +
	"\x1bSHOP_TYPE_PERSONAL_EXCHANGE\x10\x02B<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_shop_type_proto_rawDescOnce sync.Once
	file_shop_type_proto_rawDescData []byte
)

func file_shop_type_proto_rawDescGZIP() []byte {
	file_shop_type_proto_rawDescOnce.Do(func() {
		file_shop_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_type_proto_rawDesc), len(file_shop_type_proto_rawDesc)))
	})
	return file_shop_type_proto_rawDescData
}

var file_shop_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shop_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shop_type_proto_goTypes = []any{
	(ShopType)(0),        // 0: zeus.game.shop.v1.ShopType
	(*ShopItem)(nil),     // 1: zeus.game.shop.v1.ShopItem
	(*ShopItemList)(nil), // 2: zeus.game.shop.v1.ShopItemList
	(*ItemInfo)(nil),     // 3: zeus.game.item.v1.ItemInfo
	(*ItemPrice)(nil),    // 4: zeus.game.item.v1.ItemPrice
}
var file_shop_type_proto_depIdxs = []int32{
	3, // 0: zeus.game.shop.v1.ShopItem.info:type_name -> zeus.game.item.v1.ItemInfo
	4, // 1: zeus.game.shop.v1.ShopItem.prices:type_name -> zeus.game.item.v1.ItemPrice
	0, // 2: zeus.game.shop.v1.ShopItemList.shop_type:type_name -> zeus.game.shop.v1.ShopType
	1, // 3: zeus.game.shop.v1.ShopItemList.items:type_name -> zeus.game.shop.v1.ShopItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shop_type_proto_init() }
func file_shop_type_proto_init() {
	if File_shop_type_proto != nil {
		return
	}
	file_item_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_type_proto_rawDesc), len(file_shop_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_type_proto_goTypes,
		DependencyIndexes: file_shop_type_proto_depIdxs,
		EnumInfos:         file_shop_type_proto_enumTypes,
		MessageInfos:      file_shop_type_proto_msgTypes,
	}.Build()
	File_shop_type_proto = out.File
	file_shop_type_proto_goTypes = nil
	file_shop_type_proto_depIdxs = nil
}
