// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: shop.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取商城商品列表 - 请求
type GetShopItemListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopType      ShopType               `protobuf:"varint,1,opt,name=shop_type,json=shopType,proto3,enum=zeus.game.shop.v1.ShopType" json:"shop_type,omitempty"` // 要查询的商店类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopItemListRequest) Reset() {
	*x = GetShopItemListRequest{}
	mi := &file_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopItemListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopItemListRequest) ProtoMessage() {}

func (x *GetShopItemListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopItemListRequest.ProtoReflect.Descriptor instead.
func (*GetShopItemListRequest) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

func (x *GetShopItemListRequest) GetShopType() ShopType {
	if x != nil {
		return x.ShopType
	}
	return ShopType_SHOP_TYPE_UNKNOWN
}

// 获取商城商品列表 - 响应
type GetShopItemListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *ShopItemList          `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"` // 对应商店的道具列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopItemListResponse) Reset() {
	*x = GetShopItemListResponse{}
	mi := &file_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopItemListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopItemListResponse) ProtoMessage() {}

func (x *GetShopItemListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopItemListResponse.ProtoReflect.Descriptor instead.
func (*GetShopItemListResponse) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

func (x *GetShopItemListResponse) GetList() *ShopItemList {
	if x != nil {
		return x.List
	}
	return nil
}

// 购买商品 - 请求
type BuyShopItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                       // 要购买的商品（配置 ID）
	Num           uint64                 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                                                           // 购买数量
	ShopType      ShopType               `protobuf:"varint,3,opt,name=shop_type,json=shopType,proto3,enum=zeus.game.shop.v1.ShopType" json:"shop_type,omitempty"` // 购买来源的商店类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyShopItemRequest) Reset() {
	*x = BuyShopItemRequest{}
	mi := &file_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyShopItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyShopItemRequest) ProtoMessage() {}

func (x *BuyShopItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyShopItemRequest.ProtoReflect.Descriptor instead.
func (*BuyShopItemRequest) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{2}
}

func (x *BuyShopItemRequest) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BuyShopItemRequest) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyShopItemRequest) GetShopType() ShopType {
	if x != nil {
		return x.ShopType
	}
	return ShopType_SHOP_TYPE_UNKNOWN
}

// 购买商品 - 响应
type BuyShopItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                                                        // 错误信息（库存不足、货币不足等）
	ItemId        uint64                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                                       // 购买的商品配置 ID
	Num           uint64                 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`                                                           // 实际购买数量
	ShopType      ShopType               `protobuf:"varint,4,opt,name=shop_type,json=shopType,proto3,enum=zeus.game.shop.v1.ShopType" json:"shop_type,omitempty"` // 商店类型，用于前端更新对应商店
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyShopItemResponse) Reset() {
	*x = BuyShopItemResponse{}
	mi := &file_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyShopItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyShopItemResponse) ProtoMessage() {}

func (x *BuyShopItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyShopItemResponse.ProtoReflect.Descriptor instead.
func (*BuyShopItemResponse) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{3}
}

func (x *BuyShopItemResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *BuyShopItemResponse) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BuyShopItemResponse) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyShopItemResponse) GetShopType() ShopType {
	if x != nil {
		return x.ShopType
	}
	return ShopType_SHOP_TYPE_UNKNOWN
}

var File_shop_proto protoreflect.FileDescriptor

const file_shop_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shop.proto\x12\x11zeus.game.shop.v1\x1a\x0eerr_code.proto\x1a\x0fshop_type.proto\"R\n" +
	"\x16GetShopItemListRequest\x128\n" +
	"\tshop_type\x18\x01 \x01(\x0e2\x1b.zeus.game.shop.v1.ShopTypeR\bshopType\"N\n" +
	"\x17GetShopItemListResponse\x123\n" +
	"\x04list\x18\x01 \x01(\v2\x1f.zeus.game.shop.v1.ShopItemListR\x04list\"y\n" +
	"\x12BuyShopItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x04R\x06itemId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x04R\x03num\x128\n" +
	"\tshop_type\x18\x03 \x01(\x0e2\x1b.zeus.game.shop.v1.ShopTypeR\bshopType\"\xab\x01\n" +
	"\x13BuyShopItemResponse\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.zeus.game.error.v1.ErrorR\x05error\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x04R\x06itemId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x04R\x03num\x128\n" +
	"\tshop_type\x18\x04 \x01(\x0e2\x1b.zeus.game.shop.v1.ShopTypeR\bshopTypeB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_shop_proto_rawDescOnce sync.Once
	file_shop_proto_rawDescData []byte
)

func file_shop_proto_rawDescGZIP() []byte {
	file_shop_proto_rawDescOnce.Do(func() {
		file_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)))
	})
	return file_shop_proto_rawDescData
}

var file_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shop_proto_goTypes = []any{
	(*GetShopItemListRequest)(nil),  // 0: zeus.game.shop.v1.GetShopItemListRequest
	(*GetShopItemListResponse)(nil), // 1: zeus.game.shop.v1.GetShopItemListResponse
	(*BuyShopItemRequest)(nil),      // 2: zeus.game.shop.v1.BuyShopItemRequest
	(*BuyShopItemResponse)(nil),     // 3: zeus.game.shop.v1.BuyShopItemResponse
	(ShopType)(0),                   // 4: zeus.game.shop.v1.ShopType
	(*ShopItemList)(nil),            // 5: zeus.game.shop.v1.ShopItemList
	(*Error)(nil),                   // 6: zeus.game.error.v1.Error
}
var file_shop_proto_depIdxs = []int32{
	4, // 0: zeus.game.shop.v1.GetShopItemListRequest.shop_type:type_name -> zeus.game.shop.v1.ShopType
	5, // 1: zeus.game.shop.v1.GetShopItemListResponse.list:type_name -> zeus.game.shop.v1.ShopItemList
	4, // 2: zeus.game.shop.v1.BuyShopItemRequest.shop_type:type_name -> zeus.game.shop.v1.ShopType
	6, // 3: zeus.game.shop.v1.BuyShopItemResponse.error:type_name -> zeus.game.error.v1.Error
	4, // 4: zeus.game.shop.v1.BuyShopItemResponse.shop_type:type_name -> zeus.game.shop.v1.ShopType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shop_proto_init() }
func file_shop_proto_init() {
	if File_shop_proto != nil {
		return
	}
	file_err_code_proto_init()
	file_shop_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_proto_goTypes,
		DependencyIndexes: file_shop_proto_depIdxs,
		MessageInfos:      file_shop_proto_msgTypes,
	}.Build()
	File_shop_proto = out.File
	file_shop_proto_goTypes = nil
	file_shop_proto_depIdxs = nil
}
