// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: vip_type.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家当前 VIP 信息
type VipInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrExp           uint64                 `protobuf:"varint,1,opt,name=curr_exp,json=currExp,proto3" json:"curr_exp,omitempty"`                                 // 当前累计成长值（由钻石消费折算）
	TodayEnergyEarned int64                  `protobuf:"varint,2,opt,name=today_energy_earned,json=todayEnergyEarned,proto3" json:"today_energy_earned,omitempty"` // 今日已获得的装饰能量
	// 当月装饰能量清零时间（例如每月最后一天 24 点）
	MonthResetTime int64 `protobuf:"varint,3,opt,name=month_reset_time,json=monthResetTime,proto3" json:"month_reset_time,omitempty"` // 时间戳（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VipInfo) Reset() {
	*x = VipInfo{}
	mi := &file_vip_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipInfo) ProtoMessage() {}

func (x *VipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vip_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipInfo.ProtoReflect.Descriptor instead.
func (*VipInfo) Descriptor() ([]byte, []int) {
	return file_vip_type_proto_rawDescGZIP(), []int{0}
}

func (x *VipInfo) GetCurrExp() uint64 {
	if x != nil {
		return x.CurrExp
	}
	return 0
}

func (x *VipInfo) GetTodayEnergyEarned() int64 {
	if x != nil {
		return x.TodayEnergyEarned
	}
	return 0
}

func (x *VipInfo) GetMonthResetTime() int64 {
	if x != nil {
		return x.MonthResetTime
	}
	return 0
}

var File_vip_type_proto protoreflect.FileDescriptor

const file_vip_type_proto_rawDesc = "" +
	"\n" +
	"\x0evip_type.proto\x12\x10zeus.game.vip.v1\"~\n" +
	"\aVipInfo\x12\x19\n" +
	"\bcurr_exp\x18\x01 \x01(\x04R\acurrExp\x12.\n" +
	"\x13today_energy_earned\x18\x02 \x01(\x03R\x11todayEnergyEarned\x12(\n" +
	"\x10month_reset_time\x18\x03 \x01(\x03R\x0emonthResetTimeB<Z:github.com/lk2023060901/danmu-garden-game-protos;frameworkb\x06proto3"

var (
	file_vip_type_proto_rawDescOnce sync.Once
	file_vip_type_proto_rawDescData []byte
)

func file_vip_type_proto_rawDescGZIP() []byte {
	file_vip_type_proto_rawDescOnce.Do(func() {
		file_vip_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vip_type_proto_rawDesc), len(file_vip_type_proto_rawDesc)))
	})
	return file_vip_type_proto_rawDescData
}

var file_vip_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vip_type_proto_goTypes = []any{
	(*VipInfo)(nil), // 0: zeus.game.vip.v1.VipInfo
}
var file_vip_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vip_type_proto_init() }
func file_vip_type_proto_init() {
	if File_vip_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vip_type_proto_rawDesc), len(file_vip_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vip_type_proto_goTypes,
		DependencyIndexes: file_vip_type_proto_depIdxs,
		MessageInfos:      file_vip_type_proto_msgTypes,
	}.Build()
	File_vip_type_proto = out.File
	file_vip_type_proto_goTypes = nil
	file_vip_type_proto_depIdxs = nil
}
